// Generated by jextract

package io.github.ghosthack.panama.media.d3d11video.jextract;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct _DXVA_PicParams_H264 {
 *     USHORT wFrameWidthInMbsMinus1;
 *     USHORT wFrameHeightInMbsMinus1;
 *     DXVA_PicEntry_H264 CurrPic;
 *     UCHAR num_ref_frames;
 *     union {
 *         struct {
 *             USHORT field_pic_flag : 1;
 *             USHORT MbaffFrameFlag : 1;
 *             USHORT residual_colour_transform_flag : 1;
 *             USHORT sp_for_switch_flag : 1;
 *             USHORT chroma_format_idc : 2;
 *             USHORT RefPicFlag : 1;
 *             USHORT constrained_intra_pred_flag : 1;
 *             USHORT weighted_pred_flag : 1;
 *             USHORT weighted_bipred_idc : 2;
 *             USHORT MbsConsecutiveFlag : 1;
 *             USHORT frame_mbs_only_flag : 1;
 *             USHORT transform_8x8_mode_flag : 1;
 *             USHORT MinLumaBipredSize8x8Flag : 1;
 *             USHORT IntraPicFlag : 1;
 *         };
 *         USHORT wBitFields;
 *     };
 *     UCHAR bit_depth_luma_minus8;
 *     UCHAR bit_depth_chroma_minus8;
 *     USHORT Reserved16Bits;
 *     UINT StatusReportFeedbackNumber;
 *     DXVA_PicEntry_H264 RefFrameList[16];
 *     INT CurrFieldOrderCnt[2];
 *     INT FieldOrderCntList[16][2];
 *     CHAR pic_init_qs_minus26;
 *     CHAR chroma_qp_index_offset;
 *     CHAR second_chroma_qp_index_offset;
 *     UCHAR ContinuationFlag;
 *     CHAR pic_init_qp_minus26;
 *     UCHAR num_ref_idx_l0_active_minus1;
 *     UCHAR num_ref_idx_l1_active_minus1;
 *     UCHAR Reserved8BitsA;
 *     USHORT FrameNumList[16];
 *     UINT UsedForReferenceFlags;
 *     USHORT NonExistingFrameFlags;
 *     USHORT frame_num;
 *     UCHAR log2_max_frame_num_minus4;
 *     UCHAR pic_order_cnt_type;
 *     UCHAR log2_max_pic_order_cnt_lsb_minus4;
 *     UCHAR delta_pic_order_always_zero_flag;
 *     UCHAR direct_8x8_inference_flag;
 *     UCHAR entropy_coding_mode_flag;
 *     UCHAR pic_order_present_flag;
 *     UCHAR num_slice_groups_minus1;
 *     UCHAR slice_group_map_type;
 *     UCHAR deblocking_filter_control_present_flag;
 *     UCHAR redundant_pic_cnt_present_flag;
 *     UCHAR Reserved8BitsB;
 *     USHORT slice_group_change_rate_minus1;
 *     UCHAR SliceGroupMap[810];
 * }
 * }
 */
public class _DXVA_PicParams_H264 {

    _DXVA_PicParams_H264() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        d3d11video_h.align(d3d11video_h.C_SHORT, 1).withName("wFrameWidthInMbsMinus1"),
        d3d11video_h.align(d3d11video_h.C_SHORT, 1).withName("wFrameHeightInMbsMinus1"),
        _DXVA_PicEntry_H264.layout().withName("CurrPic"),
        d3d11video_h.C_CHAR.withName("num_ref_frames"),
        MemoryLayout.unionLayout(
            MemoryLayout.structLayout(
                MemoryLayout.paddingLayout(2)
            ).withName("$anon$734:5"),
            d3d11video_h.align(d3d11video_h.C_SHORT, 1).withName("wBitFields")
        ).withName("$anon$733:3"),
        d3d11video_h.C_CHAR.withName("bit_depth_luma_minus8"),
        d3d11video_h.C_CHAR.withName("bit_depth_chroma_minus8"),
        d3d11video_h.align(d3d11video_h.C_SHORT, 1).withName("Reserved16Bits"),
        d3d11video_h.align(d3d11video_h.C_INT, 1).withName("StatusReportFeedbackNumber"),
        MemoryLayout.sequenceLayout(16, _DXVA_PicEntry_H264.layout()).withName("RefFrameList"),
        MemoryLayout.sequenceLayout(2, d3d11video_h.align(d3d11video_h.C_INT, 1)).withName("CurrFieldOrderCnt"),
        MemoryLayout.sequenceLayout(16, MemoryLayout.sequenceLayout(2, d3d11video_h.align(d3d11video_h.C_INT, 1))).withName("FieldOrderCntList"),
        d3d11video_h.C_CHAR.withName("pic_init_qs_minus26"),
        d3d11video_h.C_CHAR.withName("chroma_qp_index_offset"),
        d3d11video_h.C_CHAR.withName("second_chroma_qp_index_offset"),
        d3d11video_h.C_CHAR.withName("ContinuationFlag"),
        d3d11video_h.C_CHAR.withName("pic_init_qp_minus26"),
        d3d11video_h.C_CHAR.withName("num_ref_idx_l0_active_minus1"),
        d3d11video_h.C_CHAR.withName("num_ref_idx_l1_active_minus1"),
        d3d11video_h.C_CHAR.withName("Reserved8BitsA"),
        MemoryLayout.sequenceLayout(16, d3d11video_h.align(d3d11video_h.C_SHORT, 1)).withName("FrameNumList"),
        d3d11video_h.align(d3d11video_h.C_INT, 1).withName("UsedForReferenceFlags"),
        d3d11video_h.align(d3d11video_h.C_SHORT, 1).withName("NonExistingFrameFlags"),
        d3d11video_h.align(d3d11video_h.C_SHORT, 1).withName("frame_num"),
        d3d11video_h.C_CHAR.withName("log2_max_frame_num_minus4"),
        d3d11video_h.C_CHAR.withName("pic_order_cnt_type"),
        d3d11video_h.C_CHAR.withName("log2_max_pic_order_cnt_lsb_minus4"),
        d3d11video_h.C_CHAR.withName("delta_pic_order_always_zero_flag"),
        d3d11video_h.C_CHAR.withName("direct_8x8_inference_flag"),
        d3d11video_h.C_CHAR.withName("entropy_coding_mode_flag"),
        d3d11video_h.C_CHAR.withName("pic_order_present_flag"),
        d3d11video_h.C_CHAR.withName("num_slice_groups_minus1"),
        d3d11video_h.C_CHAR.withName("slice_group_map_type"),
        d3d11video_h.C_CHAR.withName("deblocking_filter_control_present_flag"),
        d3d11video_h.C_CHAR.withName("redundant_pic_cnt_present_flag"),
        d3d11video_h.C_CHAR.withName("Reserved8BitsB"),
        d3d11video_h.align(d3d11video_h.C_SHORT, 1).withName("slice_group_change_rate_minus1"),
        MemoryLayout.sequenceLayout(810, d3d11video_h.C_CHAR).withName("SliceGroupMap")
    ).withName("_DXVA_PicParams_H264");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfShort wFrameWidthInMbsMinus1$LAYOUT = (OfShort)$LAYOUT.select(groupElement("wFrameWidthInMbsMinus1"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * USHORT wFrameWidthInMbsMinus1
     * }
     */
    public static final OfShort wFrameWidthInMbsMinus1$layout() {
        return wFrameWidthInMbsMinus1$LAYOUT;
    }

    private static final long wFrameWidthInMbsMinus1$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * USHORT wFrameWidthInMbsMinus1
     * }
     */
    public static final long wFrameWidthInMbsMinus1$offset() {
        return wFrameWidthInMbsMinus1$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * USHORT wFrameWidthInMbsMinus1
     * }
     */
    public static short wFrameWidthInMbsMinus1(MemorySegment struct) {
        return struct.get(wFrameWidthInMbsMinus1$LAYOUT, wFrameWidthInMbsMinus1$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * USHORT wFrameWidthInMbsMinus1
     * }
     */
    public static void wFrameWidthInMbsMinus1(MemorySegment struct, short fieldValue) {
        struct.set(wFrameWidthInMbsMinus1$LAYOUT, wFrameWidthInMbsMinus1$OFFSET, fieldValue);
    }

    private static final OfShort wFrameHeightInMbsMinus1$LAYOUT = (OfShort)$LAYOUT.select(groupElement("wFrameHeightInMbsMinus1"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * USHORT wFrameHeightInMbsMinus1
     * }
     */
    public static final OfShort wFrameHeightInMbsMinus1$layout() {
        return wFrameHeightInMbsMinus1$LAYOUT;
    }

    private static final long wFrameHeightInMbsMinus1$OFFSET = 2;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * USHORT wFrameHeightInMbsMinus1
     * }
     */
    public static final long wFrameHeightInMbsMinus1$offset() {
        return wFrameHeightInMbsMinus1$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * USHORT wFrameHeightInMbsMinus1
     * }
     */
    public static short wFrameHeightInMbsMinus1(MemorySegment struct) {
        return struct.get(wFrameHeightInMbsMinus1$LAYOUT, wFrameHeightInMbsMinus1$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * USHORT wFrameHeightInMbsMinus1
     * }
     */
    public static void wFrameHeightInMbsMinus1(MemorySegment struct, short fieldValue) {
        struct.set(wFrameHeightInMbsMinus1$LAYOUT, wFrameHeightInMbsMinus1$OFFSET, fieldValue);
    }

    private static final GroupLayout CurrPic$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("CurrPic"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * DXVA_PicEntry_H264 CurrPic
     * }
     */
    public static final GroupLayout CurrPic$layout() {
        return CurrPic$LAYOUT;
    }

    private static final long CurrPic$OFFSET = 4;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * DXVA_PicEntry_H264 CurrPic
     * }
     */
    public static final long CurrPic$offset() {
        return CurrPic$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * DXVA_PicEntry_H264 CurrPic
     * }
     */
    public static MemorySegment CurrPic(MemorySegment struct) {
        return struct.asSlice(CurrPic$OFFSET, CurrPic$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * DXVA_PicEntry_H264 CurrPic
     * }
     */
    public static void CurrPic(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, CurrPic$OFFSET, CurrPic$LAYOUT.byteSize());
    }

    private static final OfByte num_ref_frames$LAYOUT = (OfByte)$LAYOUT.select(groupElement("num_ref_frames"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * UCHAR num_ref_frames
     * }
     */
    public static final OfByte num_ref_frames$layout() {
        return num_ref_frames$LAYOUT;
    }

    private static final long num_ref_frames$OFFSET = 5;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * UCHAR num_ref_frames
     * }
     */
    public static final long num_ref_frames$offset() {
        return num_ref_frames$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * UCHAR num_ref_frames
     * }
     */
    public static byte num_ref_frames(MemorySegment struct) {
        return struct.get(num_ref_frames$LAYOUT, num_ref_frames$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * UCHAR num_ref_frames
     * }
     */
    public static void num_ref_frames(MemorySegment struct, byte fieldValue) {
        struct.set(num_ref_frames$LAYOUT, num_ref_frames$OFFSET, fieldValue);
    }

    private static final OfShort wBitFields$LAYOUT = (OfShort)$LAYOUT.select(groupElement("$anon$733:3"), groupElement("wBitFields"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * USHORT wBitFields
     * }
     */
    public static final OfShort wBitFields$layout() {
        return wBitFields$LAYOUT;
    }

    private static final long wBitFields$OFFSET = 6;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * USHORT wBitFields
     * }
     */
    public static final long wBitFields$offset() {
        return wBitFields$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * USHORT wBitFields
     * }
     */
    public static short wBitFields(MemorySegment struct) {
        return struct.get(wBitFields$LAYOUT, wBitFields$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * USHORT wBitFields
     * }
     */
    public static void wBitFields(MemorySegment struct, short fieldValue) {
        struct.set(wBitFields$LAYOUT, wBitFields$OFFSET, fieldValue);
    }

    private static final OfByte bit_depth_luma_minus8$LAYOUT = (OfByte)$LAYOUT.select(groupElement("bit_depth_luma_minus8"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * UCHAR bit_depth_luma_minus8
     * }
     */
    public static final OfByte bit_depth_luma_minus8$layout() {
        return bit_depth_luma_minus8$LAYOUT;
    }

    private static final long bit_depth_luma_minus8$OFFSET = 8;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * UCHAR bit_depth_luma_minus8
     * }
     */
    public static final long bit_depth_luma_minus8$offset() {
        return bit_depth_luma_minus8$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * UCHAR bit_depth_luma_minus8
     * }
     */
    public static byte bit_depth_luma_minus8(MemorySegment struct) {
        return struct.get(bit_depth_luma_minus8$LAYOUT, bit_depth_luma_minus8$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * UCHAR bit_depth_luma_minus8
     * }
     */
    public static void bit_depth_luma_minus8(MemorySegment struct, byte fieldValue) {
        struct.set(bit_depth_luma_minus8$LAYOUT, bit_depth_luma_minus8$OFFSET, fieldValue);
    }

    private static final OfByte bit_depth_chroma_minus8$LAYOUT = (OfByte)$LAYOUT.select(groupElement("bit_depth_chroma_minus8"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * UCHAR bit_depth_chroma_minus8
     * }
     */
    public static final OfByte bit_depth_chroma_minus8$layout() {
        return bit_depth_chroma_minus8$LAYOUT;
    }

    private static final long bit_depth_chroma_minus8$OFFSET = 9;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * UCHAR bit_depth_chroma_minus8
     * }
     */
    public static final long bit_depth_chroma_minus8$offset() {
        return bit_depth_chroma_minus8$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * UCHAR bit_depth_chroma_minus8
     * }
     */
    public static byte bit_depth_chroma_minus8(MemorySegment struct) {
        return struct.get(bit_depth_chroma_minus8$LAYOUT, bit_depth_chroma_minus8$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * UCHAR bit_depth_chroma_minus8
     * }
     */
    public static void bit_depth_chroma_minus8(MemorySegment struct, byte fieldValue) {
        struct.set(bit_depth_chroma_minus8$LAYOUT, bit_depth_chroma_minus8$OFFSET, fieldValue);
    }

    private static final OfShort Reserved16Bits$LAYOUT = (OfShort)$LAYOUT.select(groupElement("Reserved16Bits"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * USHORT Reserved16Bits
     * }
     */
    public static final OfShort Reserved16Bits$layout() {
        return Reserved16Bits$LAYOUT;
    }

    private static final long Reserved16Bits$OFFSET = 10;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * USHORT Reserved16Bits
     * }
     */
    public static final long Reserved16Bits$offset() {
        return Reserved16Bits$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * USHORT Reserved16Bits
     * }
     */
    public static short Reserved16Bits(MemorySegment struct) {
        return struct.get(Reserved16Bits$LAYOUT, Reserved16Bits$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * USHORT Reserved16Bits
     * }
     */
    public static void Reserved16Bits(MemorySegment struct, short fieldValue) {
        struct.set(Reserved16Bits$LAYOUT, Reserved16Bits$OFFSET, fieldValue);
    }

    private static final OfInt StatusReportFeedbackNumber$LAYOUT = (OfInt)$LAYOUT.select(groupElement("StatusReportFeedbackNumber"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * UINT StatusReportFeedbackNumber
     * }
     */
    public static final OfInt StatusReportFeedbackNumber$layout() {
        return StatusReportFeedbackNumber$LAYOUT;
    }

    private static final long StatusReportFeedbackNumber$OFFSET = 12;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * UINT StatusReportFeedbackNumber
     * }
     */
    public static final long StatusReportFeedbackNumber$offset() {
        return StatusReportFeedbackNumber$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * UINT StatusReportFeedbackNumber
     * }
     */
    public static int StatusReportFeedbackNumber(MemorySegment struct) {
        return struct.get(StatusReportFeedbackNumber$LAYOUT, StatusReportFeedbackNumber$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * UINT StatusReportFeedbackNumber
     * }
     */
    public static void StatusReportFeedbackNumber(MemorySegment struct, int fieldValue) {
        struct.set(StatusReportFeedbackNumber$LAYOUT, StatusReportFeedbackNumber$OFFSET, fieldValue);
    }

    private static final SequenceLayout RefFrameList$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("RefFrameList"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * DXVA_PicEntry_H264 RefFrameList[16]
     * }
     */
    public static final SequenceLayout RefFrameList$layout() {
        return RefFrameList$LAYOUT;
    }

    private static final long RefFrameList$OFFSET = 16;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * DXVA_PicEntry_H264 RefFrameList[16]
     * }
     */
    public static final long RefFrameList$offset() {
        return RefFrameList$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * DXVA_PicEntry_H264 RefFrameList[16]
     * }
     */
    public static MemorySegment RefFrameList(MemorySegment struct) {
        return struct.asSlice(RefFrameList$OFFSET, RefFrameList$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * DXVA_PicEntry_H264 RefFrameList[16]
     * }
     */
    public static void RefFrameList(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, RefFrameList$OFFSET, RefFrameList$LAYOUT.byteSize());
    }

    private static long[] RefFrameList$DIMS = { 16 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * DXVA_PicEntry_H264 RefFrameList[16]
     * }
     */
    public static long[] RefFrameList$dimensions() {
        return RefFrameList$DIMS;
    }
    private static final MethodHandle RefFrameList$ELEM_HANDLE = RefFrameList$LAYOUT.sliceHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * DXVA_PicEntry_H264 RefFrameList[16]
     * }
     */
    public static MemorySegment RefFrameList(MemorySegment struct, long index0) {
        try {
            return (MemorySegment)RefFrameList$ELEM_HANDLE.invokeExact(struct, 0L, index0);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * DXVA_PicEntry_H264 RefFrameList[16]
     * }
     */
    public static void RefFrameList(MemorySegment struct, long index0, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, RefFrameList(struct, index0), 0L, _DXVA_PicEntry_H264.layout().byteSize());
    }

    private static final SequenceLayout CurrFieldOrderCnt$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("CurrFieldOrderCnt"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * INT CurrFieldOrderCnt[2]
     * }
     */
    public static final SequenceLayout CurrFieldOrderCnt$layout() {
        return CurrFieldOrderCnt$LAYOUT;
    }

    private static final long CurrFieldOrderCnt$OFFSET = 32;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * INT CurrFieldOrderCnt[2]
     * }
     */
    public static final long CurrFieldOrderCnt$offset() {
        return CurrFieldOrderCnt$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * INT CurrFieldOrderCnt[2]
     * }
     */
    public static MemorySegment CurrFieldOrderCnt(MemorySegment struct) {
        return struct.asSlice(CurrFieldOrderCnt$OFFSET, CurrFieldOrderCnt$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * INT CurrFieldOrderCnt[2]
     * }
     */
    public static void CurrFieldOrderCnt(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, CurrFieldOrderCnt$OFFSET, CurrFieldOrderCnt$LAYOUT.byteSize());
    }

    private static long[] CurrFieldOrderCnt$DIMS = { 2 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * INT CurrFieldOrderCnt[2]
     * }
     */
    public static long[] CurrFieldOrderCnt$dimensions() {
        return CurrFieldOrderCnt$DIMS;
    }
    private static final VarHandle CurrFieldOrderCnt$ELEM_HANDLE = CurrFieldOrderCnt$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * INT CurrFieldOrderCnt[2]
     * }
     */
    public static int CurrFieldOrderCnt(MemorySegment struct, long index0) {
        return (int)CurrFieldOrderCnt$ELEM_HANDLE.get(struct, 0L, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * INT CurrFieldOrderCnt[2]
     * }
     */
    public static void CurrFieldOrderCnt(MemorySegment struct, long index0, int fieldValue) {
        CurrFieldOrderCnt$ELEM_HANDLE.set(struct, 0L, index0, fieldValue);
    }

    private static final SequenceLayout FieldOrderCntList$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("FieldOrderCntList"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * INT FieldOrderCntList[16][2]
     * }
     */
    public static final SequenceLayout FieldOrderCntList$layout() {
        return FieldOrderCntList$LAYOUT;
    }

    private static final long FieldOrderCntList$OFFSET = 40;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * INT FieldOrderCntList[16][2]
     * }
     */
    public static final long FieldOrderCntList$offset() {
        return FieldOrderCntList$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * INT FieldOrderCntList[16][2]
     * }
     */
    public static MemorySegment FieldOrderCntList(MemorySegment struct) {
        return struct.asSlice(FieldOrderCntList$OFFSET, FieldOrderCntList$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * INT FieldOrderCntList[16][2]
     * }
     */
    public static void FieldOrderCntList(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, FieldOrderCntList$OFFSET, FieldOrderCntList$LAYOUT.byteSize());
    }

    private static long[] FieldOrderCntList$DIMS = { 16, 2 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * INT FieldOrderCntList[16][2]
     * }
     */
    public static long[] FieldOrderCntList$dimensions() {
        return FieldOrderCntList$DIMS;
    }
    private static final VarHandle FieldOrderCntList$ELEM_HANDLE = FieldOrderCntList$LAYOUT.varHandle(sequenceElement(), sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * INT FieldOrderCntList[16][2]
     * }
     */
    public static int FieldOrderCntList(MemorySegment struct, long index0, long index1) {
        return (int)FieldOrderCntList$ELEM_HANDLE.get(struct, 0L, index0, index1);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * INT FieldOrderCntList[16][2]
     * }
     */
    public static void FieldOrderCntList(MemorySegment struct, long index0, long index1, int fieldValue) {
        FieldOrderCntList$ELEM_HANDLE.set(struct, 0L, index0, index1, fieldValue);
    }

    private static final OfByte pic_init_qs_minus26$LAYOUT = (OfByte)$LAYOUT.select(groupElement("pic_init_qs_minus26"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * CHAR pic_init_qs_minus26
     * }
     */
    public static final OfByte pic_init_qs_minus26$layout() {
        return pic_init_qs_minus26$LAYOUT;
    }

    private static final long pic_init_qs_minus26$OFFSET = 168;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * CHAR pic_init_qs_minus26
     * }
     */
    public static final long pic_init_qs_minus26$offset() {
        return pic_init_qs_minus26$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * CHAR pic_init_qs_minus26
     * }
     */
    public static byte pic_init_qs_minus26(MemorySegment struct) {
        return struct.get(pic_init_qs_minus26$LAYOUT, pic_init_qs_minus26$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * CHAR pic_init_qs_minus26
     * }
     */
    public static void pic_init_qs_minus26(MemorySegment struct, byte fieldValue) {
        struct.set(pic_init_qs_minus26$LAYOUT, pic_init_qs_minus26$OFFSET, fieldValue);
    }

    private static final OfByte chroma_qp_index_offset$LAYOUT = (OfByte)$LAYOUT.select(groupElement("chroma_qp_index_offset"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * CHAR chroma_qp_index_offset
     * }
     */
    public static final OfByte chroma_qp_index_offset$layout() {
        return chroma_qp_index_offset$LAYOUT;
    }

    private static final long chroma_qp_index_offset$OFFSET = 169;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * CHAR chroma_qp_index_offset
     * }
     */
    public static final long chroma_qp_index_offset$offset() {
        return chroma_qp_index_offset$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * CHAR chroma_qp_index_offset
     * }
     */
    public static byte chroma_qp_index_offset(MemorySegment struct) {
        return struct.get(chroma_qp_index_offset$LAYOUT, chroma_qp_index_offset$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * CHAR chroma_qp_index_offset
     * }
     */
    public static void chroma_qp_index_offset(MemorySegment struct, byte fieldValue) {
        struct.set(chroma_qp_index_offset$LAYOUT, chroma_qp_index_offset$OFFSET, fieldValue);
    }

    private static final OfByte second_chroma_qp_index_offset$LAYOUT = (OfByte)$LAYOUT.select(groupElement("second_chroma_qp_index_offset"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * CHAR second_chroma_qp_index_offset
     * }
     */
    public static final OfByte second_chroma_qp_index_offset$layout() {
        return second_chroma_qp_index_offset$LAYOUT;
    }

    private static final long second_chroma_qp_index_offset$OFFSET = 170;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * CHAR second_chroma_qp_index_offset
     * }
     */
    public static final long second_chroma_qp_index_offset$offset() {
        return second_chroma_qp_index_offset$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * CHAR second_chroma_qp_index_offset
     * }
     */
    public static byte second_chroma_qp_index_offset(MemorySegment struct) {
        return struct.get(second_chroma_qp_index_offset$LAYOUT, second_chroma_qp_index_offset$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * CHAR second_chroma_qp_index_offset
     * }
     */
    public static void second_chroma_qp_index_offset(MemorySegment struct, byte fieldValue) {
        struct.set(second_chroma_qp_index_offset$LAYOUT, second_chroma_qp_index_offset$OFFSET, fieldValue);
    }

    private static final OfByte ContinuationFlag$LAYOUT = (OfByte)$LAYOUT.select(groupElement("ContinuationFlag"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * UCHAR ContinuationFlag
     * }
     */
    public static final OfByte ContinuationFlag$layout() {
        return ContinuationFlag$LAYOUT;
    }

    private static final long ContinuationFlag$OFFSET = 171;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * UCHAR ContinuationFlag
     * }
     */
    public static final long ContinuationFlag$offset() {
        return ContinuationFlag$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * UCHAR ContinuationFlag
     * }
     */
    public static byte ContinuationFlag(MemorySegment struct) {
        return struct.get(ContinuationFlag$LAYOUT, ContinuationFlag$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * UCHAR ContinuationFlag
     * }
     */
    public static void ContinuationFlag(MemorySegment struct, byte fieldValue) {
        struct.set(ContinuationFlag$LAYOUT, ContinuationFlag$OFFSET, fieldValue);
    }

    private static final OfByte pic_init_qp_minus26$LAYOUT = (OfByte)$LAYOUT.select(groupElement("pic_init_qp_minus26"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * CHAR pic_init_qp_minus26
     * }
     */
    public static final OfByte pic_init_qp_minus26$layout() {
        return pic_init_qp_minus26$LAYOUT;
    }

    private static final long pic_init_qp_minus26$OFFSET = 172;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * CHAR pic_init_qp_minus26
     * }
     */
    public static final long pic_init_qp_minus26$offset() {
        return pic_init_qp_minus26$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * CHAR pic_init_qp_minus26
     * }
     */
    public static byte pic_init_qp_minus26(MemorySegment struct) {
        return struct.get(pic_init_qp_minus26$LAYOUT, pic_init_qp_minus26$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * CHAR pic_init_qp_minus26
     * }
     */
    public static void pic_init_qp_minus26(MemorySegment struct, byte fieldValue) {
        struct.set(pic_init_qp_minus26$LAYOUT, pic_init_qp_minus26$OFFSET, fieldValue);
    }

    private static final OfByte num_ref_idx_l0_active_minus1$LAYOUT = (OfByte)$LAYOUT.select(groupElement("num_ref_idx_l0_active_minus1"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * UCHAR num_ref_idx_l0_active_minus1
     * }
     */
    public static final OfByte num_ref_idx_l0_active_minus1$layout() {
        return num_ref_idx_l0_active_minus1$LAYOUT;
    }

    private static final long num_ref_idx_l0_active_minus1$OFFSET = 173;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * UCHAR num_ref_idx_l0_active_minus1
     * }
     */
    public static final long num_ref_idx_l0_active_minus1$offset() {
        return num_ref_idx_l0_active_minus1$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * UCHAR num_ref_idx_l0_active_minus1
     * }
     */
    public static byte num_ref_idx_l0_active_minus1(MemorySegment struct) {
        return struct.get(num_ref_idx_l0_active_minus1$LAYOUT, num_ref_idx_l0_active_minus1$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * UCHAR num_ref_idx_l0_active_minus1
     * }
     */
    public static void num_ref_idx_l0_active_minus1(MemorySegment struct, byte fieldValue) {
        struct.set(num_ref_idx_l0_active_minus1$LAYOUT, num_ref_idx_l0_active_minus1$OFFSET, fieldValue);
    }

    private static final OfByte num_ref_idx_l1_active_minus1$LAYOUT = (OfByte)$LAYOUT.select(groupElement("num_ref_idx_l1_active_minus1"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * UCHAR num_ref_idx_l1_active_minus1
     * }
     */
    public static final OfByte num_ref_idx_l1_active_minus1$layout() {
        return num_ref_idx_l1_active_minus1$LAYOUT;
    }

    private static final long num_ref_idx_l1_active_minus1$OFFSET = 174;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * UCHAR num_ref_idx_l1_active_minus1
     * }
     */
    public static final long num_ref_idx_l1_active_minus1$offset() {
        return num_ref_idx_l1_active_minus1$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * UCHAR num_ref_idx_l1_active_minus1
     * }
     */
    public static byte num_ref_idx_l1_active_minus1(MemorySegment struct) {
        return struct.get(num_ref_idx_l1_active_minus1$LAYOUT, num_ref_idx_l1_active_minus1$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * UCHAR num_ref_idx_l1_active_minus1
     * }
     */
    public static void num_ref_idx_l1_active_minus1(MemorySegment struct, byte fieldValue) {
        struct.set(num_ref_idx_l1_active_minus1$LAYOUT, num_ref_idx_l1_active_minus1$OFFSET, fieldValue);
    }

    private static final OfByte Reserved8BitsA$LAYOUT = (OfByte)$LAYOUT.select(groupElement("Reserved8BitsA"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * UCHAR Reserved8BitsA
     * }
     */
    public static final OfByte Reserved8BitsA$layout() {
        return Reserved8BitsA$LAYOUT;
    }

    private static final long Reserved8BitsA$OFFSET = 175;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * UCHAR Reserved8BitsA
     * }
     */
    public static final long Reserved8BitsA$offset() {
        return Reserved8BitsA$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * UCHAR Reserved8BitsA
     * }
     */
    public static byte Reserved8BitsA(MemorySegment struct) {
        return struct.get(Reserved8BitsA$LAYOUT, Reserved8BitsA$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * UCHAR Reserved8BitsA
     * }
     */
    public static void Reserved8BitsA(MemorySegment struct, byte fieldValue) {
        struct.set(Reserved8BitsA$LAYOUT, Reserved8BitsA$OFFSET, fieldValue);
    }

    private static final SequenceLayout FrameNumList$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("FrameNumList"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * USHORT FrameNumList[16]
     * }
     */
    public static final SequenceLayout FrameNumList$layout() {
        return FrameNumList$LAYOUT;
    }

    private static final long FrameNumList$OFFSET = 176;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * USHORT FrameNumList[16]
     * }
     */
    public static final long FrameNumList$offset() {
        return FrameNumList$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * USHORT FrameNumList[16]
     * }
     */
    public static MemorySegment FrameNumList(MemorySegment struct) {
        return struct.asSlice(FrameNumList$OFFSET, FrameNumList$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * USHORT FrameNumList[16]
     * }
     */
    public static void FrameNumList(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, FrameNumList$OFFSET, FrameNumList$LAYOUT.byteSize());
    }

    private static long[] FrameNumList$DIMS = { 16 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * USHORT FrameNumList[16]
     * }
     */
    public static long[] FrameNumList$dimensions() {
        return FrameNumList$DIMS;
    }
    private static final VarHandle FrameNumList$ELEM_HANDLE = FrameNumList$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * USHORT FrameNumList[16]
     * }
     */
    public static short FrameNumList(MemorySegment struct, long index0) {
        return (short)FrameNumList$ELEM_HANDLE.get(struct, 0L, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * USHORT FrameNumList[16]
     * }
     */
    public static void FrameNumList(MemorySegment struct, long index0, short fieldValue) {
        FrameNumList$ELEM_HANDLE.set(struct, 0L, index0, fieldValue);
    }

    private static final OfInt UsedForReferenceFlags$LAYOUT = (OfInt)$LAYOUT.select(groupElement("UsedForReferenceFlags"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * UINT UsedForReferenceFlags
     * }
     */
    public static final OfInt UsedForReferenceFlags$layout() {
        return UsedForReferenceFlags$LAYOUT;
    }

    private static final long UsedForReferenceFlags$OFFSET = 208;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * UINT UsedForReferenceFlags
     * }
     */
    public static final long UsedForReferenceFlags$offset() {
        return UsedForReferenceFlags$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * UINT UsedForReferenceFlags
     * }
     */
    public static int UsedForReferenceFlags(MemorySegment struct) {
        return struct.get(UsedForReferenceFlags$LAYOUT, UsedForReferenceFlags$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * UINT UsedForReferenceFlags
     * }
     */
    public static void UsedForReferenceFlags(MemorySegment struct, int fieldValue) {
        struct.set(UsedForReferenceFlags$LAYOUT, UsedForReferenceFlags$OFFSET, fieldValue);
    }

    private static final OfShort NonExistingFrameFlags$LAYOUT = (OfShort)$LAYOUT.select(groupElement("NonExistingFrameFlags"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * USHORT NonExistingFrameFlags
     * }
     */
    public static final OfShort NonExistingFrameFlags$layout() {
        return NonExistingFrameFlags$LAYOUT;
    }

    private static final long NonExistingFrameFlags$OFFSET = 212;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * USHORT NonExistingFrameFlags
     * }
     */
    public static final long NonExistingFrameFlags$offset() {
        return NonExistingFrameFlags$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * USHORT NonExistingFrameFlags
     * }
     */
    public static short NonExistingFrameFlags(MemorySegment struct) {
        return struct.get(NonExistingFrameFlags$LAYOUT, NonExistingFrameFlags$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * USHORT NonExistingFrameFlags
     * }
     */
    public static void NonExistingFrameFlags(MemorySegment struct, short fieldValue) {
        struct.set(NonExistingFrameFlags$LAYOUT, NonExistingFrameFlags$OFFSET, fieldValue);
    }

    private static final OfShort frame_num$LAYOUT = (OfShort)$LAYOUT.select(groupElement("frame_num"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * USHORT frame_num
     * }
     */
    public static final OfShort frame_num$layout() {
        return frame_num$LAYOUT;
    }

    private static final long frame_num$OFFSET = 214;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * USHORT frame_num
     * }
     */
    public static final long frame_num$offset() {
        return frame_num$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * USHORT frame_num
     * }
     */
    public static short frame_num(MemorySegment struct) {
        return struct.get(frame_num$LAYOUT, frame_num$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * USHORT frame_num
     * }
     */
    public static void frame_num(MemorySegment struct, short fieldValue) {
        struct.set(frame_num$LAYOUT, frame_num$OFFSET, fieldValue);
    }

    private static final OfByte log2_max_frame_num_minus4$LAYOUT = (OfByte)$LAYOUT.select(groupElement("log2_max_frame_num_minus4"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * UCHAR log2_max_frame_num_minus4
     * }
     */
    public static final OfByte log2_max_frame_num_minus4$layout() {
        return log2_max_frame_num_minus4$LAYOUT;
    }

    private static final long log2_max_frame_num_minus4$OFFSET = 216;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * UCHAR log2_max_frame_num_minus4
     * }
     */
    public static final long log2_max_frame_num_minus4$offset() {
        return log2_max_frame_num_minus4$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * UCHAR log2_max_frame_num_minus4
     * }
     */
    public static byte log2_max_frame_num_minus4(MemorySegment struct) {
        return struct.get(log2_max_frame_num_minus4$LAYOUT, log2_max_frame_num_minus4$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * UCHAR log2_max_frame_num_minus4
     * }
     */
    public static void log2_max_frame_num_minus4(MemorySegment struct, byte fieldValue) {
        struct.set(log2_max_frame_num_minus4$LAYOUT, log2_max_frame_num_minus4$OFFSET, fieldValue);
    }

    private static final OfByte pic_order_cnt_type$LAYOUT = (OfByte)$LAYOUT.select(groupElement("pic_order_cnt_type"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * UCHAR pic_order_cnt_type
     * }
     */
    public static final OfByte pic_order_cnt_type$layout() {
        return pic_order_cnt_type$LAYOUT;
    }

    private static final long pic_order_cnt_type$OFFSET = 217;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * UCHAR pic_order_cnt_type
     * }
     */
    public static final long pic_order_cnt_type$offset() {
        return pic_order_cnt_type$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * UCHAR pic_order_cnt_type
     * }
     */
    public static byte pic_order_cnt_type(MemorySegment struct) {
        return struct.get(pic_order_cnt_type$LAYOUT, pic_order_cnt_type$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * UCHAR pic_order_cnt_type
     * }
     */
    public static void pic_order_cnt_type(MemorySegment struct, byte fieldValue) {
        struct.set(pic_order_cnt_type$LAYOUT, pic_order_cnt_type$OFFSET, fieldValue);
    }

    private static final OfByte log2_max_pic_order_cnt_lsb_minus4$LAYOUT = (OfByte)$LAYOUT.select(groupElement("log2_max_pic_order_cnt_lsb_minus4"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * UCHAR log2_max_pic_order_cnt_lsb_minus4
     * }
     */
    public static final OfByte log2_max_pic_order_cnt_lsb_minus4$layout() {
        return log2_max_pic_order_cnt_lsb_minus4$LAYOUT;
    }

    private static final long log2_max_pic_order_cnt_lsb_minus4$OFFSET = 218;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * UCHAR log2_max_pic_order_cnt_lsb_minus4
     * }
     */
    public static final long log2_max_pic_order_cnt_lsb_minus4$offset() {
        return log2_max_pic_order_cnt_lsb_minus4$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * UCHAR log2_max_pic_order_cnt_lsb_minus4
     * }
     */
    public static byte log2_max_pic_order_cnt_lsb_minus4(MemorySegment struct) {
        return struct.get(log2_max_pic_order_cnt_lsb_minus4$LAYOUT, log2_max_pic_order_cnt_lsb_minus4$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * UCHAR log2_max_pic_order_cnt_lsb_minus4
     * }
     */
    public static void log2_max_pic_order_cnt_lsb_minus4(MemorySegment struct, byte fieldValue) {
        struct.set(log2_max_pic_order_cnt_lsb_minus4$LAYOUT, log2_max_pic_order_cnt_lsb_minus4$OFFSET, fieldValue);
    }

    private static final OfByte delta_pic_order_always_zero_flag$LAYOUT = (OfByte)$LAYOUT.select(groupElement("delta_pic_order_always_zero_flag"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * UCHAR delta_pic_order_always_zero_flag
     * }
     */
    public static final OfByte delta_pic_order_always_zero_flag$layout() {
        return delta_pic_order_always_zero_flag$LAYOUT;
    }

    private static final long delta_pic_order_always_zero_flag$OFFSET = 219;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * UCHAR delta_pic_order_always_zero_flag
     * }
     */
    public static final long delta_pic_order_always_zero_flag$offset() {
        return delta_pic_order_always_zero_flag$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * UCHAR delta_pic_order_always_zero_flag
     * }
     */
    public static byte delta_pic_order_always_zero_flag(MemorySegment struct) {
        return struct.get(delta_pic_order_always_zero_flag$LAYOUT, delta_pic_order_always_zero_flag$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * UCHAR delta_pic_order_always_zero_flag
     * }
     */
    public static void delta_pic_order_always_zero_flag(MemorySegment struct, byte fieldValue) {
        struct.set(delta_pic_order_always_zero_flag$LAYOUT, delta_pic_order_always_zero_flag$OFFSET, fieldValue);
    }

    private static final OfByte direct_8x8_inference_flag$LAYOUT = (OfByte)$LAYOUT.select(groupElement("direct_8x8_inference_flag"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * UCHAR direct_8x8_inference_flag
     * }
     */
    public static final OfByte direct_8x8_inference_flag$layout() {
        return direct_8x8_inference_flag$LAYOUT;
    }

    private static final long direct_8x8_inference_flag$OFFSET = 220;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * UCHAR direct_8x8_inference_flag
     * }
     */
    public static final long direct_8x8_inference_flag$offset() {
        return direct_8x8_inference_flag$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * UCHAR direct_8x8_inference_flag
     * }
     */
    public static byte direct_8x8_inference_flag(MemorySegment struct) {
        return struct.get(direct_8x8_inference_flag$LAYOUT, direct_8x8_inference_flag$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * UCHAR direct_8x8_inference_flag
     * }
     */
    public static void direct_8x8_inference_flag(MemorySegment struct, byte fieldValue) {
        struct.set(direct_8x8_inference_flag$LAYOUT, direct_8x8_inference_flag$OFFSET, fieldValue);
    }

    private static final OfByte entropy_coding_mode_flag$LAYOUT = (OfByte)$LAYOUT.select(groupElement("entropy_coding_mode_flag"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * UCHAR entropy_coding_mode_flag
     * }
     */
    public static final OfByte entropy_coding_mode_flag$layout() {
        return entropy_coding_mode_flag$LAYOUT;
    }

    private static final long entropy_coding_mode_flag$OFFSET = 221;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * UCHAR entropy_coding_mode_flag
     * }
     */
    public static final long entropy_coding_mode_flag$offset() {
        return entropy_coding_mode_flag$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * UCHAR entropy_coding_mode_flag
     * }
     */
    public static byte entropy_coding_mode_flag(MemorySegment struct) {
        return struct.get(entropy_coding_mode_flag$LAYOUT, entropy_coding_mode_flag$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * UCHAR entropy_coding_mode_flag
     * }
     */
    public static void entropy_coding_mode_flag(MemorySegment struct, byte fieldValue) {
        struct.set(entropy_coding_mode_flag$LAYOUT, entropy_coding_mode_flag$OFFSET, fieldValue);
    }

    private static final OfByte pic_order_present_flag$LAYOUT = (OfByte)$LAYOUT.select(groupElement("pic_order_present_flag"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * UCHAR pic_order_present_flag
     * }
     */
    public static final OfByte pic_order_present_flag$layout() {
        return pic_order_present_flag$LAYOUT;
    }

    private static final long pic_order_present_flag$OFFSET = 222;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * UCHAR pic_order_present_flag
     * }
     */
    public static final long pic_order_present_flag$offset() {
        return pic_order_present_flag$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * UCHAR pic_order_present_flag
     * }
     */
    public static byte pic_order_present_flag(MemorySegment struct) {
        return struct.get(pic_order_present_flag$LAYOUT, pic_order_present_flag$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * UCHAR pic_order_present_flag
     * }
     */
    public static void pic_order_present_flag(MemorySegment struct, byte fieldValue) {
        struct.set(pic_order_present_flag$LAYOUT, pic_order_present_flag$OFFSET, fieldValue);
    }

    private static final OfByte num_slice_groups_minus1$LAYOUT = (OfByte)$LAYOUT.select(groupElement("num_slice_groups_minus1"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * UCHAR num_slice_groups_minus1
     * }
     */
    public static final OfByte num_slice_groups_minus1$layout() {
        return num_slice_groups_minus1$LAYOUT;
    }

    private static final long num_slice_groups_minus1$OFFSET = 223;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * UCHAR num_slice_groups_minus1
     * }
     */
    public static final long num_slice_groups_minus1$offset() {
        return num_slice_groups_minus1$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * UCHAR num_slice_groups_minus1
     * }
     */
    public static byte num_slice_groups_minus1(MemorySegment struct) {
        return struct.get(num_slice_groups_minus1$LAYOUT, num_slice_groups_minus1$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * UCHAR num_slice_groups_minus1
     * }
     */
    public static void num_slice_groups_minus1(MemorySegment struct, byte fieldValue) {
        struct.set(num_slice_groups_minus1$LAYOUT, num_slice_groups_minus1$OFFSET, fieldValue);
    }

    private static final OfByte slice_group_map_type$LAYOUT = (OfByte)$LAYOUT.select(groupElement("slice_group_map_type"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * UCHAR slice_group_map_type
     * }
     */
    public static final OfByte slice_group_map_type$layout() {
        return slice_group_map_type$LAYOUT;
    }

    private static final long slice_group_map_type$OFFSET = 224;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * UCHAR slice_group_map_type
     * }
     */
    public static final long slice_group_map_type$offset() {
        return slice_group_map_type$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * UCHAR slice_group_map_type
     * }
     */
    public static byte slice_group_map_type(MemorySegment struct) {
        return struct.get(slice_group_map_type$LAYOUT, slice_group_map_type$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * UCHAR slice_group_map_type
     * }
     */
    public static void slice_group_map_type(MemorySegment struct, byte fieldValue) {
        struct.set(slice_group_map_type$LAYOUT, slice_group_map_type$OFFSET, fieldValue);
    }

    private static final OfByte deblocking_filter_control_present_flag$LAYOUT = (OfByte)$LAYOUT.select(groupElement("deblocking_filter_control_present_flag"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * UCHAR deblocking_filter_control_present_flag
     * }
     */
    public static final OfByte deblocking_filter_control_present_flag$layout() {
        return deblocking_filter_control_present_flag$LAYOUT;
    }

    private static final long deblocking_filter_control_present_flag$OFFSET = 225;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * UCHAR deblocking_filter_control_present_flag
     * }
     */
    public static final long deblocking_filter_control_present_flag$offset() {
        return deblocking_filter_control_present_flag$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * UCHAR deblocking_filter_control_present_flag
     * }
     */
    public static byte deblocking_filter_control_present_flag(MemorySegment struct) {
        return struct.get(deblocking_filter_control_present_flag$LAYOUT, deblocking_filter_control_present_flag$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * UCHAR deblocking_filter_control_present_flag
     * }
     */
    public static void deblocking_filter_control_present_flag(MemorySegment struct, byte fieldValue) {
        struct.set(deblocking_filter_control_present_flag$LAYOUT, deblocking_filter_control_present_flag$OFFSET, fieldValue);
    }

    private static final OfByte redundant_pic_cnt_present_flag$LAYOUT = (OfByte)$LAYOUT.select(groupElement("redundant_pic_cnt_present_flag"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * UCHAR redundant_pic_cnt_present_flag
     * }
     */
    public static final OfByte redundant_pic_cnt_present_flag$layout() {
        return redundant_pic_cnt_present_flag$LAYOUT;
    }

    private static final long redundant_pic_cnt_present_flag$OFFSET = 226;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * UCHAR redundant_pic_cnt_present_flag
     * }
     */
    public static final long redundant_pic_cnt_present_flag$offset() {
        return redundant_pic_cnt_present_flag$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * UCHAR redundant_pic_cnt_present_flag
     * }
     */
    public static byte redundant_pic_cnt_present_flag(MemorySegment struct) {
        return struct.get(redundant_pic_cnt_present_flag$LAYOUT, redundant_pic_cnt_present_flag$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * UCHAR redundant_pic_cnt_present_flag
     * }
     */
    public static void redundant_pic_cnt_present_flag(MemorySegment struct, byte fieldValue) {
        struct.set(redundant_pic_cnt_present_flag$LAYOUT, redundant_pic_cnt_present_flag$OFFSET, fieldValue);
    }

    private static final OfByte Reserved8BitsB$LAYOUT = (OfByte)$LAYOUT.select(groupElement("Reserved8BitsB"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * UCHAR Reserved8BitsB
     * }
     */
    public static final OfByte Reserved8BitsB$layout() {
        return Reserved8BitsB$LAYOUT;
    }

    private static final long Reserved8BitsB$OFFSET = 227;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * UCHAR Reserved8BitsB
     * }
     */
    public static final long Reserved8BitsB$offset() {
        return Reserved8BitsB$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * UCHAR Reserved8BitsB
     * }
     */
    public static byte Reserved8BitsB(MemorySegment struct) {
        return struct.get(Reserved8BitsB$LAYOUT, Reserved8BitsB$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * UCHAR Reserved8BitsB
     * }
     */
    public static void Reserved8BitsB(MemorySegment struct, byte fieldValue) {
        struct.set(Reserved8BitsB$LAYOUT, Reserved8BitsB$OFFSET, fieldValue);
    }

    private static final OfShort slice_group_change_rate_minus1$LAYOUT = (OfShort)$LAYOUT.select(groupElement("slice_group_change_rate_minus1"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * USHORT slice_group_change_rate_minus1
     * }
     */
    public static final OfShort slice_group_change_rate_minus1$layout() {
        return slice_group_change_rate_minus1$LAYOUT;
    }

    private static final long slice_group_change_rate_minus1$OFFSET = 228;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * USHORT slice_group_change_rate_minus1
     * }
     */
    public static final long slice_group_change_rate_minus1$offset() {
        return slice_group_change_rate_minus1$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * USHORT slice_group_change_rate_minus1
     * }
     */
    public static short slice_group_change_rate_minus1(MemorySegment struct) {
        return struct.get(slice_group_change_rate_minus1$LAYOUT, slice_group_change_rate_minus1$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * USHORT slice_group_change_rate_minus1
     * }
     */
    public static void slice_group_change_rate_minus1(MemorySegment struct, short fieldValue) {
        struct.set(slice_group_change_rate_minus1$LAYOUT, slice_group_change_rate_minus1$OFFSET, fieldValue);
    }

    private static final SequenceLayout SliceGroupMap$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("SliceGroupMap"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * UCHAR SliceGroupMap[810]
     * }
     */
    public static final SequenceLayout SliceGroupMap$layout() {
        return SliceGroupMap$LAYOUT;
    }

    private static final long SliceGroupMap$OFFSET = 230;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * UCHAR SliceGroupMap[810]
     * }
     */
    public static final long SliceGroupMap$offset() {
        return SliceGroupMap$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * UCHAR SliceGroupMap[810]
     * }
     */
    public static MemorySegment SliceGroupMap(MemorySegment struct) {
        return struct.asSlice(SliceGroupMap$OFFSET, SliceGroupMap$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * UCHAR SliceGroupMap[810]
     * }
     */
    public static void SliceGroupMap(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, SliceGroupMap$OFFSET, SliceGroupMap$LAYOUT.byteSize());
    }

    private static long[] SliceGroupMap$DIMS = { 810 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * UCHAR SliceGroupMap[810]
     * }
     */
    public static long[] SliceGroupMap$dimensions() {
        return SliceGroupMap$DIMS;
    }
    private static final VarHandle SliceGroupMap$ELEM_HANDLE = SliceGroupMap$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * UCHAR SliceGroupMap[810]
     * }
     */
    public static byte SliceGroupMap(MemorySegment struct, long index0) {
        return (byte)SliceGroupMap$ELEM_HANDLE.get(struct, 0L, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * UCHAR SliceGroupMap[810]
     * }
     */
    public static void SliceGroupMap(MemorySegment struct, long index0, byte fieldValue) {
        SliceGroupMap$ELEM_HANDLE.set(struct, 0L, index0, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

