// Generated by jextract

package io.github.ghosthack.panama.media.d3d11video.jextract;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct _DXVA_Qmatrix_H264 {
 *     UCHAR bScalingLists4x4[6][16];
 *     UCHAR bScalingLists8x8[2][64];
 * }
 * }
 */
public class _DXVA_Qmatrix_H264 {

    _DXVA_Qmatrix_H264() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        MemoryLayout.sequenceLayout(6, MemoryLayout.sequenceLayout(16, d3d11video_h.C_CHAR)).withName("bScalingLists4x4"),
        MemoryLayout.sequenceLayout(2, MemoryLayout.sequenceLayout(64, d3d11video_h.C_CHAR)).withName("bScalingLists8x8")
    ).withName("_DXVA_Qmatrix_H264");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final SequenceLayout bScalingLists4x4$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("bScalingLists4x4"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * UCHAR bScalingLists4x4[6][16]
     * }
     */
    public static final SequenceLayout bScalingLists4x4$layout() {
        return bScalingLists4x4$LAYOUT;
    }

    private static final long bScalingLists4x4$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * UCHAR bScalingLists4x4[6][16]
     * }
     */
    public static final long bScalingLists4x4$offset() {
        return bScalingLists4x4$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * UCHAR bScalingLists4x4[6][16]
     * }
     */
    public static MemorySegment bScalingLists4x4(MemorySegment struct) {
        return struct.asSlice(bScalingLists4x4$OFFSET, bScalingLists4x4$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * UCHAR bScalingLists4x4[6][16]
     * }
     */
    public static void bScalingLists4x4(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, bScalingLists4x4$OFFSET, bScalingLists4x4$LAYOUT.byteSize());
    }

    private static long[] bScalingLists4x4$DIMS = { 6, 16 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * UCHAR bScalingLists4x4[6][16]
     * }
     */
    public static long[] bScalingLists4x4$dimensions() {
        return bScalingLists4x4$DIMS;
    }
    private static final VarHandle bScalingLists4x4$ELEM_HANDLE = bScalingLists4x4$LAYOUT.varHandle(sequenceElement(), sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * UCHAR bScalingLists4x4[6][16]
     * }
     */
    public static byte bScalingLists4x4(MemorySegment struct, long index0, long index1) {
        return (byte)bScalingLists4x4$ELEM_HANDLE.get(struct, 0L, index0, index1);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * UCHAR bScalingLists4x4[6][16]
     * }
     */
    public static void bScalingLists4x4(MemorySegment struct, long index0, long index1, byte fieldValue) {
        bScalingLists4x4$ELEM_HANDLE.set(struct, 0L, index0, index1, fieldValue);
    }

    private static final SequenceLayout bScalingLists8x8$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("bScalingLists8x8"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * UCHAR bScalingLists8x8[2][64]
     * }
     */
    public static final SequenceLayout bScalingLists8x8$layout() {
        return bScalingLists8x8$LAYOUT;
    }

    private static final long bScalingLists8x8$OFFSET = 96;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * UCHAR bScalingLists8x8[2][64]
     * }
     */
    public static final long bScalingLists8x8$offset() {
        return bScalingLists8x8$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * UCHAR bScalingLists8x8[2][64]
     * }
     */
    public static MemorySegment bScalingLists8x8(MemorySegment struct) {
        return struct.asSlice(bScalingLists8x8$OFFSET, bScalingLists8x8$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * UCHAR bScalingLists8x8[2][64]
     * }
     */
    public static void bScalingLists8x8(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, bScalingLists8x8$OFFSET, bScalingLists8x8$LAYOUT.byteSize());
    }

    private static long[] bScalingLists8x8$DIMS = { 2, 64 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * UCHAR bScalingLists8x8[2][64]
     * }
     */
    public static long[] bScalingLists8x8$dimensions() {
        return bScalingLists8x8$DIMS;
    }
    private static final VarHandle bScalingLists8x8$ELEM_HANDLE = bScalingLists8x8$LAYOUT.varHandle(sequenceElement(), sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * UCHAR bScalingLists8x8[2][64]
     * }
     */
    public static byte bScalingLists8x8(MemorySegment struct, long index0, long index1) {
        return (byte)bScalingLists8x8$ELEM_HANDLE.get(struct, 0L, index0, index1);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * UCHAR bScalingLists8x8[2][64]
     * }
     */
    public static void bScalingLists8x8(MemorySegment struct, long index0, long index1, byte fieldValue) {
        bScalingLists8x8$ELEM_HANDLE.set(struct, 0L, index0, index1, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

