// Generated by jextract

package io.github.ghosthack.panama.media.d3d11video.jextract;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct _DXVA_Slice_H264_Short {
 *     UINT BSNALunitDataLocation;
 *     UINT SliceBytesInBuffer;
 *     USHORT wBadSliceChopping;
 * }
 * }
 */
public class _DXVA_Slice_H264_Short {

    _DXVA_Slice_H264_Short() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        d3d11video_h.align(d3d11video_h.C_INT, 1).withName("BSNALunitDataLocation"),
        d3d11video_h.align(d3d11video_h.C_INT, 1).withName("SliceBytesInBuffer"),
        d3d11video_h.align(d3d11video_h.C_SHORT, 1).withName("wBadSliceChopping")
    ).withName("_DXVA_Slice_H264_Short");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt BSNALunitDataLocation$LAYOUT = (OfInt)$LAYOUT.select(groupElement("BSNALunitDataLocation"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * UINT BSNALunitDataLocation
     * }
     */
    public static final OfInt BSNALunitDataLocation$layout() {
        return BSNALunitDataLocation$LAYOUT;
    }

    private static final long BSNALunitDataLocation$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * UINT BSNALunitDataLocation
     * }
     */
    public static final long BSNALunitDataLocation$offset() {
        return BSNALunitDataLocation$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * UINT BSNALunitDataLocation
     * }
     */
    public static int BSNALunitDataLocation(MemorySegment struct) {
        return struct.get(BSNALunitDataLocation$LAYOUT, BSNALunitDataLocation$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * UINT BSNALunitDataLocation
     * }
     */
    public static void BSNALunitDataLocation(MemorySegment struct, int fieldValue) {
        struct.set(BSNALunitDataLocation$LAYOUT, BSNALunitDataLocation$OFFSET, fieldValue);
    }

    private static final OfInt SliceBytesInBuffer$LAYOUT = (OfInt)$LAYOUT.select(groupElement("SliceBytesInBuffer"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * UINT SliceBytesInBuffer
     * }
     */
    public static final OfInt SliceBytesInBuffer$layout() {
        return SliceBytesInBuffer$LAYOUT;
    }

    private static final long SliceBytesInBuffer$OFFSET = 4;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * UINT SliceBytesInBuffer
     * }
     */
    public static final long SliceBytesInBuffer$offset() {
        return SliceBytesInBuffer$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * UINT SliceBytesInBuffer
     * }
     */
    public static int SliceBytesInBuffer(MemorySegment struct) {
        return struct.get(SliceBytesInBuffer$LAYOUT, SliceBytesInBuffer$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * UINT SliceBytesInBuffer
     * }
     */
    public static void SliceBytesInBuffer(MemorySegment struct, int fieldValue) {
        struct.set(SliceBytesInBuffer$LAYOUT, SliceBytesInBuffer$OFFSET, fieldValue);
    }

    private static final OfShort wBadSliceChopping$LAYOUT = (OfShort)$LAYOUT.select(groupElement("wBadSliceChopping"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * USHORT wBadSliceChopping
     * }
     */
    public static final OfShort wBadSliceChopping$layout() {
        return wBadSliceChopping$LAYOUT;
    }

    private static final long wBadSliceChopping$OFFSET = 8;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * USHORT wBadSliceChopping
     * }
     */
    public static final long wBadSliceChopping$offset() {
        return wBadSliceChopping$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * USHORT wBadSliceChopping
     * }
     */
    public static short wBadSliceChopping(MemorySegment struct) {
        return struct.get(wBadSliceChopping$LAYOUT, wBadSliceChopping$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * USHORT wBadSliceChopping
     * }
     */
    public static void wBadSliceChopping(MemorySegment struct, short fieldValue) {
        struct.set(wBadSliceChopping$LAYOUT, wBadSliceChopping$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

