// Generated by jextract

package io.github.ghosthack.panama.media.d3d11video.jextract;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct D3D11_ENCRYPTED_BLOCK_INFO {
 *     UINT NumEncryptedBytesAtBeginning;
 *     UINT NumBytesInSkipPattern;
 *     UINT NumBytesInEncryptPattern;
 * }
 * }
 */
public class D3D11_ENCRYPTED_BLOCK_INFO {

    D3D11_ENCRYPTED_BLOCK_INFO() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        d3d11video_h.C_INT.withName("NumEncryptedBytesAtBeginning"),
        d3d11video_h.C_INT.withName("NumBytesInSkipPattern"),
        d3d11video_h.C_INT.withName("NumBytesInEncryptPattern")
    ).withName("D3D11_ENCRYPTED_BLOCK_INFO");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt NumEncryptedBytesAtBeginning$LAYOUT = (OfInt)$LAYOUT.select(groupElement("NumEncryptedBytesAtBeginning"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * UINT NumEncryptedBytesAtBeginning
     * }
     */
    public static final OfInt NumEncryptedBytesAtBeginning$layout() {
        return NumEncryptedBytesAtBeginning$LAYOUT;
    }

    private static final long NumEncryptedBytesAtBeginning$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * UINT NumEncryptedBytesAtBeginning
     * }
     */
    public static final long NumEncryptedBytesAtBeginning$offset() {
        return NumEncryptedBytesAtBeginning$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * UINT NumEncryptedBytesAtBeginning
     * }
     */
    public static int NumEncryptedBytesAtBeginning(MemorySegment struct) {
        return struct.get(NumEncryptedBytesAtBeginning$LAYOUT, NumEncryptedBytesAtBeginning$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * UINT NumEncryptedBytesAtBeginning
     * }
     */
    public static void NumEncryptedBytesAtBeginning(MemorySegment struct, int fieldValue) {
        struct.set(NumEncryptedBytesAtBeginning$LAYOUT, NumEncryptedBytesAtBeginning$OFFSET, fieldValue);
    }

    private static final OfInt NumBytesInSkipPattern$LAYOUT = (OfInt)$LAYOUT.select(groupElement("NumBytesInSkipPattern"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * UINT NumBytesInSkipPattern
     * }
     */
    public static final OfInt NumBytesInSkipPattern$layout() {
        return NumBytesInSkipPattern$LAYOUT;
    }

    private static final long NumBytesInSkipPattern$OFFSET = 4;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * UINT NumBytesInSkipPattern
     * }
     */
    public static final long NumBytesInSkipPattern$offset() {
        return NumBytesInSkipPattern$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * UINT NumBytesInSkipPattern
     * }
     */
    public static int NumBytesInSkipPattern(MemorySegment struct) {
        return struct.get(NumBytesInSkipPattern$LAYOUT, NumBytesInSkipPattern$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * UINT NumBytesInSkipPattern
     * }
     */
    public static void NumBytesInSkipPattern(MemorySegment struct, int fieldValue) {
        struct.set(NumBytesInSkipPattern$LAYOUT, NumBytesInSkipPattern$OFFSET, fieldValue);
    }

    private static final OfInt NumBytesInEncryptPattern$LAYOUT = (OfInt)$LAYOUT.select(groupElement("NumBytesInEncryptPattern"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * UINT NumBytesInEncryptPattern
     * }
     */
    public static final OfInt NumBytesInEncryptPattern$layout() {
        return NumBytesInEncryptPattern$LAYOUT;
    }

    private static final long NumBytesInEncryptPattern$OFFSET = 8;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * UINT NumBytesInEncryptPattern
     * }
     */
    public static final long NumBytesInEncryptPattern$offset() {
        return NumBytesInEncryptPattern$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * UINT NumBytesInEncryptPattern
     * }
     */
    public static int NumBytesInEncryptPattern(MemorySegment struct) {
        return struct.get(NumBytesInEncryptPattern$LAYOUT, NumBytesInEncryptPattern$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * UINT NumBytesInEncryptPattern
     * }
     */
    public static void NumBytesInEncryptPattern(MemorySegment struct, int fieldValue) {
        struct.set(NumBytesInEncryptPattern$LAYOUT, NumBytesInEncryptPattern$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

