// Generated by jextract

package io.github.ghosthack.panama.media.d3d11video.jextract;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct D3D11_MAPPED_SUBRESOURCE {
 *     void *pData;
 *     UINT RowPitch;
 *     UINT DepthPitch;
 * }
 * }
 */
public class D3D11_MAPPED_SUBRESOURCE {

    D3D11_MAPPED_SUBRESOURCE() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        d3d11video_h.C_POINTER.withName("pData"),
        d3d11video_h.C_INT.withName("RowPitch"),
        d3d11video_h.C_INT.withName("DepthPitch")
    ).withName("D3D11_MAPPED_SUBRESOURCE");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final AddressLayout pData$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("pData"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * void *pData
     * }
     */
    public static final AddressLayout pData$layout() {
        return pData$LAYOUT;
    }

    private static final long pData$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * void *pData
     * }
     */
    public static final long pData$offset() {
        return pData$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * void *pData
     * }
     */
    public static MemorySegment pData(MemorySegment struct) {
        return struct.get(pData$LAYOUT, pData$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * void *pData
     * }
     */
    public static void pData(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(pData$LAYOUT, pData$OFFSET, fieldValue);
    }

    private static final OfInt RowPitch$LAYOUT = (OfInt)$LAYOUT.select(groupElement("RowPitch"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * UINT RowPitch
     * }
     */
    public static final OfInt RowPitch$layout() {
        return RowPitch$LAYOUT;
    }

    private static final long RowPitch$OFFSET = 8;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * UINT RowPitch
     * }
     */
    public static final long RowPitch$offset() {
        return RowPitch$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * UINT RowPitch
     * }
     */
    public static int RowPitch(MemorySegment struct) {
        return struct.get(RowPitch$LAYOUT, RowPitch$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * UINT RowPitch
     * }
     */
    public static void RowPitch(MemorySegment struct, int fieldValue) {
        struct.set(RowPitch$LAYOUT, RowPitch$OFFSET, fieldValue);
    }

    private static final OfInt DepthPitch$LAYOUT = (OfInt)$LAYOUT.select(groupElement("DepthPitch"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * UINT DepthPitch
     * }
     */
    public static final OfInt DepthPitch$layout() {
        return DepthPitch$LAYOUT;
    }

    private static final long DepthPitch$OFFSET = 12;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * UINT DepthPitch
     * }
     */
    public static final long DepthPitch$offset() {
        return DepthPitch$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * UINT DepthPitch
     * }
     */
    public static int DepthPitch(MemorySegment struct) {
        return struct.get(DepthPitch$LAYOUT, DepthPitch$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * UINT DepthPitch
     * }
     */
    public static void DepthPitch(MemorySegment struct, int fieldValue) {
        struct.set(DepthPitch$LAYOUT, DepthPitch$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}
