// Generated by jextract

package io.github.ghosthack.panama.media.d3d11video.jextract;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct D3D11_VIDEO_DECODER_BUFFER_DESC {
 *     D3D11_VIDEO_DECODER_BUFFER_TYPE BufferType;
 *     UINT BufferIndex;
 *     UINT DataOffset;
 *     UINT DataSize;
 *     UINT FirstMBaddress;
 *     UINT NumMBsInBuffer;
 *     UINT Width;
 *     UINT Height;
 *     UINT Stride;
 *     UINT ReservedBits;
 *     void *pIV;
 *     UINT IVSize;
 *     BOOL PartialEncryption;
 *     D3D11_ENCRYPTED_BLOCK_INFO EncryptedBlockInfo;
 * }
 * }
 */
public class D3D11_VIDEO_DECODER_BUFFER_DESC {

    D3D11_VIDEO_DECODER_BUFFER_DESC() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        d3d11video_h.C_INT.withName("BufferType"),
        d3d11video_h.C_INT.withName("BufferIndex"),
        d3d11video_h.C_INT.withName("DataOffset"),
        d3d11video_h.C_INT.withName("DataSize"),
        d3d11video_h.C_INT.withName("FirstMBaddress"),
        d3d11video_h.C_INT.withName("NumMBsInBuffer"),
        d3d11video_h.C_INT.withName("Width"),
        d3d11video_h.C_INT.withName("Height"),
        d3d11video_h.C_INT.withName("Stride"),
        d3d11video_h.C_INT.withName("ReservedBits"),
        d3d11video_h.C_POINTER.withName("pIV"),
        d3d11video_h.C_INT.withName("IVSize"),
        d3d11video_h.C_INT.withName("PartialEncryption"),
        D3D11_ENCRYPTED_BLOCK_INFO.layout().withName("EncryptedBlockInfo"),
        MemoryLayout.paddingLayout(4)
    ).withName("D3D11_VIDEO_DECODER_BUFFER_DESC");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt BufferType$LAYOUT = (OfInt)$LAYOUT.select(groupElement("BufferType"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * D3D11_VIDEO_DECODER_BUFFER_TYPE BufferType
     * }
     */
    public static final OfInt BufferType$layout() {
        return BufferType$LAYOUT;
    }

    private static final long BufferType$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * D3D11_VIDEO_DECODER_BUFFER_TYPE BufferType
     * }
     */
    public static final long BufferType$offset() {
        return BufferType$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * D3D11_VIDEO_DECODER_BUFFER_TYPE BufferType
     * }
     */
    public static int BufferType(MemorySegment struct) {
        return struct.get(BufferType$LAYOUT, BufferType$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * D3D11_VIDEO_DECODER_BUFFER_TYPE BufferType
     * }
     */
    public static void BufferType(MemorySegment struct, int fieldValue) {
        struct.set(BufferType$LAYOUT, BufferType$OFFSET, fieldValue);
    }

    private static final OfInt BufferIndex$LAYOUT = (OfInt)$LAYOUT.select(groupElement("BufferIndex"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * UINT BufferIndex
     * }
     */
    public static final OfInt BufferIndex$layout() {
        return BufferIndex$LAYOUT;
    }

    private static final long BufferIndex$OFFSET = 4;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * UINT BufferIndex
     * }
     */
    public static final long BufferIndex$offset() {
        return BufferIndex$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * UINT BufferIndex
     * }
     */
    public static int BufferIndex(MemorySegment struct) {
        return struct.get(BufferIndex$LAYOUT, BufferIndex$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * UINT BufferIndex
     * }
     */
    public static void BufferIndex(MemorySegment struct, int fieldValue) {
        struct.set(BufferIndex$LAYOUT, BufferIndex$OFFSET, fieldValue);
    }

    private static final OfInt DataOffset$LAYOUT = (OfInt)$LAYOUT.select(groupElement("DataOffset"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * UINT DataOffset
     * }
     */
    public static final OfInt DataOffset$layout() {
        return DataOffset$LAYOUT;
    }

    private static final long DataOffset$OFFSET = 8;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * UINT DataOffset
     * }
     */
    public static final long DataOffset$offset() {
        return DataOffset$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * UINT DataOffset
     * }
     */
    public static int DataOffset(MemorySegment struct) {
        return struct.get(DataOffset$LAYOUT, DataOffset$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * UINT DataOffset
     * }
     */
    public static void DataOffset(MemorySegment struct, int fieldValue) {
        struct.set(DataOffset$LAYOUT, DataOffset$OFFSET, fieldValue);
    }

    private static final OfInt DataSize$LAYOUT = (OfInt)$LAYOUT.select(groupElement("DataSize"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * UINT DataSize
     * }
     */
    public static final OfInt DataSize$layout() {
        return DataSize$LAYOUT;
    }

    private static final long DataSize$OFFSET = 12;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * UINT DataSize
     * }
     */
    public static final long DataSize$offset() {
        return DataSize$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * UINT DataSize
     * }
     */
    public static int DataSize(MemorySegment struct) {
        return struct.get(DataSize$LAYOUT, DataSize$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * UINT DataSize
     * }
     */
    public static void DataSize(MemorySegment struct, int fieldValue) {
        struct.set(DataSize$LAYOUT, DataSize$OFFSET, fieldValue);
    }

    private static final OfInt FirstMBaddress$LAYOUT = (OfInt)$LAYOUT.select(groupElement("FirstMBaddress"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * UINT FirstMBaddress
     * }
     */
    public static final OfInt FirstMBaddress$layout() {
        return FirstMBaddress$LAYOUT;
    }

    private static final long FirstMBaddress$OFFSET = 16;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * UINT FirstMBaddress
     * }
     */
    public static final long FirstMBaddress$offset() {
        return FirstMBaddress$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * UINT FirstMBaddress
     * }
     */
    public static int FirstMBaddress(MemorySegment struct) {
        return struct.get(FirstMBaddress$LAYOUT, FirstMBaddress$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * UINT FirstMBaddress
     * }
     */
    public static void FirstMBaddress(MemorySegment struct, int fieldValue) {
        struct.set(FirstMBaddress$LAYOUT, FirstMBaddress$OFFSET, fieldValue);
    }

    private static final OfInt NumMBsInBuffer$LAYOUT = (OfInt)$LAYOUT.select(groupElement("NumMBsInBuffer"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * UINT NumMBsInBuffer
     * }
     */
    public static final OfInt NumMBsInBuffer$layout() {
        return NumMBsInBuffer$LAYOUT;
    }

    private static final long NumMBsInBuffer$OFFSET = 20;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * UINT NumMBsInBuffer
     * }
     */
    public static final long NumMBsInBuffer$offset() {
        return NumMBsInBuffer$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * UINT NumMBsInBuffer
     * }
     */
    public static int NumMBsInBuffer(MemorySegment struct) {
        return struct.get(NumMBsInBuffer$LAYOUT, NumMBsInBuffer$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * UINT NumMBsInBuffer
     * }
     */
    public static void NumMBsInBuffer(MemorySegment struct, int fieldValue) {
        struct.set(NumMBsInBuffer$LAYOUT, NumMBsInBuffer$OFFSET, fieldValue);
    }

    private static final OfInt Width$LAYOUT = (OfInt)$LAYOUT.select(groupElement("Width"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * UINT Width
     * }
     */
    public static final OfInt Width$layout() {
        return Width$LAYOUT;
    }

    private static final long Width$OFFSET = 24;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * UINT Width
     * }
     */
    public static final long Width$offset() {
        return Width$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * UINT Width
     * }
     */
    public static int Width(MemorySegment struct) {
        return struct.get(Width$LAYOUT, Width$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * UINT Width
     * }
     */
    public static void Width(MemorySegment struct, int fieldValue) {
        struct.set(Width$LAYOUT, Width$OFFSET, fieldValue);
    }

    private static final OfInt Height$LAYOUT = (OfInt)$LAYOUT.select(groupElement("Height"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * UINT Height
     * }
     */
    public static final OfInt Height$layout() {
        return Height$LAYOUT;
    }

    private static final long Height$OFFSET = 28;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * UINT Height
     * }
     */
    public static final long Height$offset() {
        return Height$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * UINT Height
     * }
     */
    public static int Height(MemorySegment struct) {
        return struct.get(Height$LAYOUT, Height$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * UINT Height
     * }
     */
    public static void Height(MemorySegment struct, int fieldValue) {
        struct.set(Height$LAYOUT, Height$OFFSET, fieldValue);
    }

    private static final OfInt Stride$LAYOUT = (OfInt)$LAYOUT.select(groupElement("Stride"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * UINT Stride
     * }
     */
    public static final OfInt Stride$layout() {
        return Stride$LAYOUT;
    }

    private static final long Stride$OFFSET = 32;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * UINT Stride
     * }
     */
    public static final long Stride$offset() {
        return Stride$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * UINT Stride
     * }
     */
    public static int Stride(MemorySegment struct) {
        return struct.get(Stride$LAYOUT, Stride$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * UINT Stride
     * }
     */
    public static void Stride(MemorySegment struct, int fieldValue) {
        struct.set(Stride$LAYOUT, Stride$OFFSET, fieldValue);
    }

    private static final OfInt ReservedBits$LAYOUT = (OfInt)$LAYOUT.select(groupElement("ReservedBits"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * UINT ReservedBits
     * }
     */
    public static final OfInt ReservedBits$layout() {
        return ReservedBits$LAYOUT;
    }

    private static final long ReservedBits$OFFSET = 36;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * UINT ReservedBits
     * }
     */
    public static final long ReservedBits$offset() {
        return ReservedBits$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * UINT ReservedBits
     * }
     */
    public static int ReservedBits(MemorySegment struct) {
        return struct.get(ReservedBits$LAYOUT, ReservedBits$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * UINT ReservedBits
     * }
     */
    public static void ReservedBits(MemorySegment struct, int fieldValue) {
        struct.set(ReservedBits$LAYOUT, ReservedBits$OFFSET, fieldValue);
    }

    private static final AddressLayout pIV$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("pIV"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * void *pIV
     * }
     */
    public static final AddressLayout pIV$layout() {
        return pIV$LAYOUT;
    }

    private static final long pIV$OFFSET = 40;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * void *pIV
     * }
     */
    public static final long pIV$offset() {
        return pIV$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * void *pIV
     * }
     */
    public static MemorySegment pIV(MemorySegment struct) {
        return struct.get(pIV$LAYOUT, pIV$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * void *pIV
     * }
     */
    public static void pIV(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(pIV$LAYOUT, pIV$OFFSET, fieldValue);
    }

    private static final OfInt IVSize$LAYOUT = (OfInt)$LAYOUT.select(groupElement("IVSize"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * UINT IVSize
     * }
     */
    public static final OfInt IVSize$layout() {
        return IVSize$LAYOUT;
    }

    private static final long IVSize$OFFSET = 48;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * UINT IVSize
     * }
     */
    public static final long IVSize$offset() {
        return IVSize$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * UINT IVSize
     * }
     */
    public static int IVSize(MemorySegment struct) {
        return struct.get(IVSize$LAYOUT, IVSize$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * UINT IVSize
     * }
     */
    public static void IVSize(MemorySegment struct, int fieldValue) {
        struct.set(IVSize$LAYOUT, IVSize$OFFSET, fieldValue);
    }

    private static final OfInt PartialEncryption$LAYOUT = (OfInt)$LAYOUT.select(groupElement("PartialEncryption"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * BOOL PartialEncryption
     * }
     */
    public static final OfInt PartialEncryption$layout() {
        return PartialEncryption$LAYOUT;
    }

    private static final long PartialEncryption$OFFSET = 52;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * BOOL PartialEncryption
     * }
     */
    public static final long PartialEncryption$offset() {
        return PartialEncryption$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * BOOL PartialEncryption
     * }
     */
    public static int PartialEncryption(MemorySegment struct) {
        return struct.get(PartialEncryption$LAYOUT, PartialEncryption$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * BOOL PartialEncryption
     * }
     */
    public static void PartialEncryption(MemorySegment struct, int fieldValue) {
        struct.set(PartialEncryption$LAYOUT, PartialEncryption$OFFSET, fieldValue);
    }

    private static final GroupLayout EncryptedBlockInfo$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("EncryptedBlockInfo"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * D3D11_ENCRYPTED_BLOCK_INFO EncryptedBlockInfo
     * }
     */
    public static final GroupLayout EncryptedBlockInfo$layout() {
        return EncryptedBlockInfo$LAYOUT;
    }

    private static final long EncryptedBlockInfo$OFFSET = 56;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * D3D11_ENCRYPTED_BLOCK_INFO EncryptedBlockInfo
     * }
     */
    public static final long EncryptedBlockInfo$offset() {
        return EncryptedBlockInfo$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * D3D11_ENCRYPTED_BLOCK_INFO EncryptedBlockInfo
     * }
     */
    public static MemorySegment EncryptedBlockInfo(MemorySegment struct) {
        return struct.asSlice(EncryptedBlockInfo$OFFSET, EncryptedBlockInfo$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * D3D11_ENCRYPTED_BLOCK_INFO EncryptedBlockInfo
     * }
     */
    public static void EncryptedBlockInfo(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, EncryptedBlockInfo$OFFSET, EncryptedBlockInfo$LAYOUT.byteSize());
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

