// Generated by jextract

package io.github.ghosthack.panama.media.d3d11video.jextract;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct D3D11_VIDEO_DECODER_CONFIG {
 *     GUID guidConfigBitstreamEncryption;
 *     GUID guidConfigMBcontrolEncryption;
 *     GUID guidConfigResidDiffEncryption;
 *     UINT ConfigBitstreamRaw;
 *     UINT ConfigMBcontrolRasterOrder;
 *     UINT ConfigResidDiffHost;
 *     UINT ConfigSpatialResid8;
 *     UINT ConfigResid8Subtraction;
 *     UINT ConfigSpatialHost8or9Clipping;
 *     UINT ConfigSpatialResidInterleaved;
 *     UINT ConfigIntraResidUnsigned;
 *     UINT ConfigResidDiffAccelerator;
 *     UINT ConfigHostInverseScan;
 *     UINT ConfigSpecificIDCT;
 *     UINT Config4GroupedCoefs;
 *     USHORT ConfigMinRenderTargetBuffCount;
 *     USHORT ConfigDecoderSpecific;
 * }
 * }
 */
public class D3D11_VIDEO_DECODER_CONFIG {

    D3D11_VIDEO_DECODER_CONFIG() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        _GUID.layout().withName("guidConfigBitstreamEncryption"),
        _GUID.layout().withName("guidConfigMBcontrolEncryption"),
        _GUID.layout().withName("guidConfigResidDiffEncryption"),
        d3d11video_h.C_INT.withName("ConfigBitstreamRaw"),
        d3d11video_h.C_INT.withName("ConfigMBcontrolRasterOrder"),
        d3d11video_h.C_INT.withName("ConfigResidDiffHost"),
        d3d11video_h.C_INT.withName("ConfigSpatialResid8"),
        d3d11video_h.C_INT.withName("ConfigResid8Subtraction"),
        d3d11video_h.C_INT.withName("ConfigSpatialHost8or9Clipping"),
        d3d11video_h.C_INT.withName("ConfigSpatialResidInterleaved"),
        d3d11video_h.C_INT.withName("ConfigIntraResidUnsigned"),
        d3d11video_h.C_INT.withName("ConfigResidDiffAccelerator"),
        d3d11video_h.C_INT.withName("ConfigHostInverseScan"),
        d3d11video_h.C_INT.withName("ConfigSpecificIDCT"),
        d3d11video_h.C_INT.withName("Config4GroupedCoefs"),
        d3d11video_h.C_SHORT.withName("ConfigMinRenderTargetBuffCount"),
        d3d11video_h.C_SHORT.withName("ConfigDecoderSpecific")
    ).withName("D3D11_VIDEO_DECODER_CONFIG");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final GroupLayout guidConfigBitstreamEncryption$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("guidConfigBitstreamEncryption"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * GUID guidConfigBitstreamEncryption
     * }
     */
    public static final GroupLayout guidConfigBitstreamEncryption$layout() {
        return guidConfigBitstreamEncryption$LAYOUT;
    }

    private static final long guidConfigBitstreamEncryption$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * GUID guidConfigBitstreamEncryption
     * }
     */
    public static final long guidConfigBitstreamEncryption$offset() {
        return guidConfigBitstreamEncryption$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * GUID guidConfigBitstreamEncryption
     * }
     */
    public static MemorySegment guidConfigBitstreamEncryption(MemorySegment struct) {
        return struct.asSlice(guidConfigBitstreamEncryption$OFFSET, guidConfigBitstreamEncryption$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * GUID guidConfigBitstreamEncryption
     * }
     */
    public static void guidConfigBitstreamEncryption(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, guidConfigBitstreamEncryption$OFFSET, guidConfigBitstreamEncryption$LAYOUT.byteSize());
    }

    private static final GroupLayout guidConfigMBcontrolEncryption$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("guidConfigMBcontrolEncryption"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * GUID guidConfigMBcontrolEncryption
     * }
     */
    public static final GroupLayout guidConfigMBcontrolEncryption$layout() {
        return guidConfigMBcontrolEncryption$LAYOUT;
    }

    private static final long guidConfigMBcontrolEncryption$OFFSET = 16;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * GUID guidConfigMBcontrolEncryption
     * }
     */
    public static final long guidConfigMBcontrolEncryption$offset() {
        return guidConfigMBcontrolEncryption$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * GUID guidConfigMBcontrolEncryption
     * }
     */
    public static MemorySegment guidConfigMBcontrolEncryption(MemorySegment struct) {
        return struct.asSlice(guidConfigMBcontrolEncryption$OFFSET, guidConfigMBcontrolEncryption$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * GUID guidConfigMBcontrolEncryption
     * }
     */
    public static void guidConfigMBcontrolEncryption(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, guidConfigMBcontrolEncryption$OFFSET, guidConfigMBcontrolEncryption$LAYOUT.byteSize());
    }

    private static final GroupLayout guidConfigResidDiffEncryption$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("guidConfigResidDiffEncryption"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * GUID guidConfigResidDiffEncryption
     * }
     */
    public static final GroupLayout guidConfigResidDiffEncryption$layout() {
        return guidConfigResidDiffEncryption$LAYOUT;
    }

    private static final long guidConfigResidDiffEncryption$OFFSET = 32;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * GUID guidConfigResidDiffEncryption
     * }
     */
    public static final long guidConfigResidDiffEncryption$offset() {
        return guidConfigResidDiffEncryption$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * GUID guidConfigResidDiffEncryption
     * }
     */
    public static MemorySegment guidConfigResidDiffEncryption(MemorySegment struct) {
        return struct.asSlice(guidConfigResidDiffEncryption$OFFSET, guidConfigResidDiffEncryption$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * GUID guidConfigResidDiffEncryption
     * }
     */
    public static void guidConfigResidDiffEncryption(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, guidConfigResidDiffEncryption$OFFSET, guidConfigResidDiffEncryption$LAYOUT.byteSize());
    }

    private static final OfInt ConfigBitstreamRaw$LAYOUT = (OfInt)$LAYOUT.select(groupElement("ConfigBitstreamRaw"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * UINT ConfigBitstreamRaw
     * }
     */
    public static final OfInt ConfigBitstreamRaw$layout() {
        return ConfigBitstreamRaw$LAYOUT;
    }

    private static final long ConfigBitstreamRaw$OFFSET = 48;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * UINT ConfigBitstreamRaw
     * }
     */
    public static final long ConfigBitstreamRaw$offset() {
        return ConfigBitstreamRaw$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * UINT ConfigBitstreamRaw
     * }
     */
    public static int ConfigBitstreamRaw(MemorySegment struct) {
        return struct.get(ConfigBitstreamRaw$LAYOUT, ConfigBitstreamRaw$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * UINT ConfigBitstreamRaw
     * }
     */
    public static void ConfigBitstreamRaw(MemorySegment struct, int fieldValue) {
        struct.set(ConfigBitstreamRaw$LAYOUT, ConfigBitstreamRaw$OFFSET, fieldValue);
    }

    private static final OfInt ConfigMBcontrolRasterOrder$LAYOUT = (OfInt)$LAYOUT.select(groupElement("ConfigMBcontrolRasterOrder"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * UINT ConfigMBcontrolRasterOrder
     * }
     */
    public static final OfInt ConfigMBcontrolRasterOrder$layout() {
        return ConfigMBcontrolRasterOrder$LAYOUT;
    }

    private static final long ConfigMBcontrolRasterOrder$OFFSET = 52;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * UINT ConfigMBcontrolRasterOrder
     * }
     */
    public static final long ConfigMBcontrolRasterOrder$offset() {
        return ConfigMBcontrolRasterOrder$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * UINT ConfigMBcontrolRasterOrder
     * }
     */
    public static int ConfigMBcontrolRasterOrder(MemorySegment struct) {
        return struct.get(ConfigMBcontrolRasterOrder$LAYOUT, ConfigMBcontrolRasterOrder$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * UINT ConfigMBcontrolRasterOrder
     * }
     */
    public static void ConfigMBcontrolRasterOrder(MemorySegment struct, int fieldValue) {
        struct.set(ConfigMBcontrolRasterOrder$LAYOUT, ConfigMBcontrolRasterOrder$OFFSET, fieldValue);
    }

    private static final OfInt ConfigResidDiffHost$LAYOUT = (OfInt)$LAYOUT.select(groupElement("ConfigResidDiffHost"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * UINT ConfigResidDiffHost
     * }
     */
    public static final OfInt ConfigResidDiffHost$layout() {
        return ConfigResidDiffHost$LAYOUT;
    }

    private static final long ConfigResidDiffHost$OFFSET = 56;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * UINT ConfigResidDiffHost
     * }
     */
    public static final long ConfigResidDiffHost$offset() {
        return ConfigResidDiffHost$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * UINT ConfigResidDiffHost
     * }
     */
    public static int ConfigResidDiffHost(MemorySegment struct) {
        return struct.get(ConfigResidDiffHost$LAYOUT, ConfigResidDiffHost$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * UINT ConfigResidDiffHost
     * }
     */
    public static void ConfigResidDiffHost(MemorySegment struct, int fieldValue) {
        struct.set(ConfigResidDiffHost$LAYOUT, ConfigResidDiffHost$OFFSET, fieldValue);
    }

    private static final OfInt ConfigSpatialResid8$LAYOUT = (OfInt)$LAYOUT.select(groupElement("ConfigSpatialResid8"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * UINT ConfigSpatialResid8
     * }
     */
    public static final OfInt ConfigSpatialResid8$layout() {
        return ConfigSpatialResid8$LAYOUT;
    }

    private static final long ConfigSpatialResid8$OFFSET = 60;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * UINT ConfigSpatialResid8
     * }
     */
    public static final long ConfigSpatialResid8$offset() {
        return ConfigSpatialResid8$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * UINT ConfigSpatialResid8
     * }
     */
    public static int ConfigSpatialResid8(MemorySegment struct) {
        return struct.get(ConfigSpatialResid8$LAYOUT, ConfigSpatialResid8$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * UINT ConfigSpatialResid8
     * }
     */
    public static void ConfigSpatialResid8(MemorySegment struct, int fieldValue) {
        struct.set(ConfigSpatialResid8$LAYOUT, ConfigSpatialResid8$OFFSET, fieldValue);
    }

    private static final OfInt ConfigResid8Subtraction$LAYOUT = (OfInt)$LAYOUT.select(groupElement("ConfigResid8Subtraction"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * UINT ConfigResid8Subtraction
     * }
     */
    public static final OfInt ConfigResid8Subtraction$layout() {
        return ConfigResid8Subtraction$LAYOUT;
    }

    private static final long ConfigResid8Subtraction$OFFSET = 64;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * UINT ConfigResid8Subtraction
     * }
     */
    public static final long ConfigResid8Subtraction$offset() {
        return ConfigResid8Subtraction$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * UINT ConfigResid8Subtraction
     * }
     */
    public static int ConfigResid8Subtraction(MemorySegment struct) {
        return struct.get(ConfigResid8Subtraction$LAYOUT, ConfigResid8Subtraction$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * UINT ConfigResid8Subtraction
     * }
     */
    public static void ConfigResid8Subtraction(MemorySegment struct, int fieldValue) {
        struct.set(ConfigResid8Subtraction$LAYOUT, ConfigResid8Subtraction$OFFSET, fieldValue);
    }

    private static final OfInt ConfigSpatialHost8or9Clipping$LAYOUT = (OfInt)$LAYOUT.select(groupElement("ConfigSpatialHost8or9Clipping"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * UINT ConfigSpatialHost8or9Clipping
     * }
     */
    public static final OfInt ConfigSpatialHost8or9Clipping$layout() {
        return ConfigSpatialHost8or9Clipping$LAYOUT;
    }

    private static final long ConfigSpatialHost8or9Clipping$OFFSET = 68;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * UINT ConfigSpatialHost8or9Clipping
     * }
     */
    public static final long ConfigSpatialHost8or9Clipping$offset() {
        return ConfigSpatialHost8or9Clipping$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * UINT ConfigSpatialHost8or9Clipping
     * }
     */
    public static int ConfigSpatialHost8or9Clipping(MemorySegment struct) {
        return struct.get(ConfigSpatialHost8or9Clipping$LAYOUT, ConfigSpatialHost8or9Clipping$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * UINT ConfigSpatialHost8or9Clipping
     * }
     */
    public static void ConfigSpatialHost8or9Clipping(MemorySegment struct, int fieldValue) {
        struct.set(ConfigSpatialHost8or9Clipping$LAYOUT, ConfigSpatialHost8or9Clipping$OFFSET, fieldValue);
    }

    private static final OfInt ConfigSpatialResidInterleaved$LAYOUT = (OfInt)$LAYOUT.select(groupElement("ConfigSpatialResidInterleaved"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * UINT ConfigSpatialResidInterleaved
     * }
     */
    public static final OfInt ConfigSpatialResidInterleaved$layout() {
        return ConfigSpatialResidInterleaved$LAYOUT;
    }

    private static final long ConfigSpatialResidInterleaved$OFFSET = 72;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * UINT ConfigSpatialResidInterleaved
     * }
     */
    public static final long ConfigSpatialResidInterleaved$offset() {
        return ConfigSpatialResidInterleaved$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * UINT ConfigSpatialResidInterleaved
     * }
     */
    public static int ConfigSpatialResidInterleaved(MemorySegment struct) {
        return struct.get(ConfigSpatialResidInterleaved$LAYOUT, ConfigSpatialResidInterleaved$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * UINT ConfigSpatialResidInterleaved
     * }
     */
    public static void ConfigSpatialResidInterleaved(MemorySegment struct, int fieldValue) {
        struct.set(ConfigSpatialResidInterleaved$LAYOUT, ConfigSpatialResidInterleaved$OFFSET, fieldValue);
    }

    private static final OfInt ConfigIntraResidUnsigned$LAYOUT = (OfInt)$LAYOUT.select(groupElement("ConfigIntraResidUnsigned"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * UINT ConfigIntraResidUnsigned
     * }
     */
    public static final OfInt ConfigIntraResidUnsigned$layout() {
        return ConfigIntraResidUnsigned$LAYOUT;
    }

    private static final long ConfigIntraResidUnsigned$OFFSET = 76;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * UINT ConfigIntraResidUnsigned
     * }
     */
    public static final long ConfigIntraResidUnsigned$offset() {
        return ConfigIntraResidUnsigned$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * UINT ConfigIntraResidUnsigned
     * }
     */
    public static int ConfigIntraResidUnsigned(MemorySegment struct) {
        return struct.get(ConfigIntraResidUnsigned$LAYOUT, ConfigIntraResidUnsigned$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * UINT ConfigIntraResidUnsigned
     * }
     */
    public static void ConfigIntraResidUnsigned(MemorySegment struct, int fieldValue) {
        struct.set(ConfigIntraResidUnsigned$LAYOUT, ConfigIntraResidUnsigned$OFFSET, fieldValue);
    }

    private static final OfInt ConfigResidDiffAccelerator$LAYOUT = (OfInt)$LAYOUT.select(groupElement("ConfigResidDiffAccelerator"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * UINT ConfigResidDiffAccelerator
     * }
     */
    public static final OfInt ConfigResidDiffAccelerator$layout() {
        return ConfigResidDiffAccelerator$LAYOUT;
    }

    private static final long ConfigResidDiffAccelerator$OFFSET = 80;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * UINT ConfigResidDiffAccelerator
     * }
     */
    public static final long ConfigResidDiffAccelerator$offset() {
        return ConfigResidDiffAccelerator$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * UINT ConfigResidDiffAccelerator
     * }
     */
    public static int ConfigResidDiffAccelerator(MemorySegment struct) {
        return struct.get(ConfigResidDiffAccelerator$LAYOUT, ConfigResidDiffAccelerator$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * UINT ConfigResidDiffAccelerator
     * }
     */
    public static void ConfigResidDiffAccelerator(MemorySegment struct, int fieldValue) {
        struct.set(ConfigResidDiffAccelerator$LAYOUT, ConfigResidDiffAccelerator$OFFSET, fieldValue);
    }

    private static final OfInt ConfigHostInverseScan$LAYOUT = (OfInt)$LAYOUT.select(groupElement("ConfigHostInverseScan"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * UINT ConfigHostInverseScan
     * }
     */
    public static final OfInt ConfigHostInverseScan$layout() {
        return ConfigHostInverseScan$LAYOUT;
    }

    private static final long ConfigHostInverseScan$OFFSET = 84;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * UINT ConfigHostInverseScan
     * }
     */
    public static final long ConfigHostInverseScan$offset() {
        return ConfigHostInverseScan$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * UINT ConfigHostInverseScan
     * }
     */
    public static int ConfigHostInverseScan(MemorySegment struct) {
        return struct.get(ConfigHostInverseScan$LAYOUT, ConfigHostInverseScan$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * UINT ConfigHostInverseScan
     * }
     */
    public static void ConfigHostInverseScan(MemorySegment struct, int fieldValue) {
        struct.set(ConfigHostInverseScan$LAYOUT, ConfigHostInverseScan$OFFSET, fieldValue);
    }

    private static final OfInt ConfigSpecificIDCT$LAYOUT = (OfInt)$LAYOUT.select(groupElement("ConfigSpecificIDCT"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * UINT ConfigSpecificIDCT
     * }
     */
    public static final OfInt ConfigSpecificIDCT$layout() {
        return ConfigSpecificIDCT$LAYOUT;
    }

    private static final long ConfigSpecificIDCT$OFFSET = 88;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * UINT ConfigSpecificIDCT
     * }
     */
    public static final long ConfigSpecificIDCT$offset() {
        return ConfigSpecificIDCT$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * UINT ConfigSpecificIDCT
     * }
     */
    public static int ConfigSpecificIDCT(MemorySegment struct) {
        return struct.get(ConfigSpecificIDCT$LAYOUT, ConfigSpecificIDCT$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * UINT ConfigSpecificIDCT
     * }
     */
    public static void ConfigSpecificIDCT(MemorySegment struct, int fieldValue) {
        struct.set(ConfigSpecificIDCT$LAYOUT, ConfigSpecificIDCT$OFFSET, fieldValue);
    }

    private static final OfInt Config4GroupedCoefs$LAYOUT = (OfInt)$LAYOUT.select(groupElement("Config4GroupedCoefs"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * UINT Config4GroupedCoefs
     * }
     */
    public static final OfInt Config4GroupedCoefs$layout() {
        return Config4GroupedCoefs$LAYOUT;
    }

    private static final long Config4GroupedCoefs$OFFSET = 92;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * UINT Config4GroupedCoefs
     * }
     */
    public static final long Config4GroupedCoefs$offset() {
        return Config4GroupedCoefs$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * UINT Config4GroupedCoefs
     * }
     */
    public static int Config4GroupedCoefs(MemorySegment struct) {
        return struct.get(Config4GroupedCoefs$LAYOUT, Config4GroupedCoefs$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * UINT Config4GroupedCoefs
     * }
     */
    public static void Config4GroupedCoefs(MemorySegment struct, int fieldValue) {
        struct.set(Config4GroupedCoefs$LAYOUT, Config4GroupedCoefs$OFFSET, fieldValue);
    }

    private static final OfShort ConfigMinRenderTargetBuffCount$LAYOUT = (OfShort)$LAYOUT.select(groupElement("ConfigMinRenderTargetBuffCount"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * USHORT ConfigMinRenderTargetBuffCount
     * }
     */
    public static final OfShort ConfigMinRenderTargetBuffCount$layout() {
        return ConfigMinRenderTargetBuffCount$LAYOUT;
    }

    private static final long ConfigMinRenderTargetBuffCount$OFFSET = 96;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * USHORT ConfigMinRenderTargetBuffCount
     * }
     */
    public static final long ConfigMinRenderTargetBuffCount$offset() {
        return ConfigMinRenderTargetBuffCount$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * USHORT ConfigMinRenderTargetBuffCount
     * }
     */
    public static short ConfigMinRenderTargetBuffCount(MemorySegment struct) {
        return struct.get(ConfigMinRenderTargetBuffCount$LAYOUT, ConfigMinRenderTargetBuffCount$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * USHORT ConfigMinRenderTargetBuffCount
     * }
     */
    public static void ConfigMinRenderTargetBuffCount(MemorySegment struct, short fieldValue) {
        struct.set(ConfigMinRenderTargetBuffCount$LAYOUT, ConfigMinRenderTargetBuffCount$OFFSET, fieldValue);
    }

    private static final OfShort ConfigDecoderSpecific$LAYOUT = (OfShort)$LAYOUT.select(groupElement("ConfigDecoderSpecific"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * USHORT ConfigDecoderSpecific
     * }
     */
    public static final OfShort ConfigDecoderSpecific$layout() {
        return ConfigDecoderSpecific$LAYOUT;
    }

    private static final long ConfigDecoderSpecific$OFFSET = 98;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * USHORT ConfigDecoderSpecific
     * }
     */
    public static final long ConfigDecoderSpecific$offset() {
        return ConfigDecoderSpecific$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * USHORT ConfigDecoderSpecific
     * }
     */
    public static short ConfigDecoderSpecific(MemorySegment struct) {
        return struct.get(ConfigDecoderSpecific$LAYOUT, ConfigDecoderSpecific$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * USHORT ConfigDecoderSpecific
     * }
     */
    public static void ConfigDecoderSpecific(MemorySegment struct, short fieldValue) {
        struct.set(ConfigDecoderSpecific$LAYOUT, ConfigDecoderSpecific$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

