// Generated by jextract

package io.github.ghosthack.panama.media.d3d11video.jextract;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct D3D11_TEXTURE2D_DESC {
 *     UINT Width;
 *     UINT Height;
 *     UINT MipLevels;
 *     UINT ArraySize;
 *     DXGI_FORMAT Format;
 *     DXGI_SAMPLE_DESC SampleDesc;
 *     D3D11_USAGE Usage;
 *     UINT BindFlags;
 *     UINT CPUAccessFlags;
 *     UINT MiscFlags;
 * }
 * }
 */
public class D3D11_TEXTURE2D_DESC {

    D3D11_TEXTURE2D_DESC() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        d3d11video_h.C_INT.withName("Width"),
        d3d11video_h.C_INT.withName("Height"),
        d3d11video_h.C_INT.withName("MipLevels"),
        d3d11video_h.C_INT.withName("ArraySize"),
        d3d11video_h.C_INT.withName("Format"),
        DXGI_SAMPLE_DESC.layout().withName("SampleDesc"),
        d3d11video_h.C_INT.withName("Usage"),
        d3d11video_h.C_INT.withName("BindFlags"),
        d3d11video_h.C_INT.withName("CPUAccessFlags"),
        d3d11video_h.C_INT.withName("MiscFlags")
    ).withName("D3D11_TEXTURE2D_DESC");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt Width$LAYOUT = (OfInt)$LAYOUT.select(groupElement("Width"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * UINT Width
     * }
     */
    public static final OfInt Width$layout() {
        return Width$LAYOUT;
    }

    private static final long Width$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * UINT Width
     * }
     */
    public static final long Width$offset() {
        return Width$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * UINT Width
     * }
     */
    public static int Width(MemorySegment struct) {
        return struct.get(Width$LAYOUT, Width$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * UINT Width
     * }
     */
    public static void Width(MemorySegment struct, int fieldValue) {
        struct.set(Width$LAYOUT, Width$OFFSET, fieldValue);
    }

    private static final OfInt Height$LAYOUT = (OfInt)$LAYOUT.select(groupElement("Height"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * UINT Height
     * }
     */
    public static final OfInt Height$layout() {
        return Height$LAYOUT;
    }

    private static final long Height$OFFSET = 4;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * UINT Height
     * }
     */
    public static final long Height$offset() {
        return Height$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * UINT Height
     * }
     */
    public static int Height(MemorySegment struct) {
        return struct.get(Height$LAYOUT, Height$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * UINT Height
     * }
     */
    public static void Height(MemorySegment struct, int fieldValue) {
        struct.set(Height$LAYOUT, Height$OFFSET, fieldValue);
    }

    private static final OfInt MipLevels$LAYOUT = (OfInt)$LAYOUT.select(groupElement("MipLevels"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * UINT MipLevels
     * }
     */
    public static final OfInt MipLevels$layout() {
        return MipLevels$LAYOUT;
    }

    private static final long MipLevels$OFFSET = 8;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * UINT MipLevels
     * }
     */
    public static final long MipLevels$offset() {
        return MipLevels$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * UINT MipLevels
     * }
     */
    public static int MipLevels(MemorySegment struct) {
        return struct.get(MipLevels$LAYOUT, MipLevels$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * UINT MipLevels
     * }
     */
    public static void MipLevels(MemorySegment struct, int fieldValue) {
        struct.set(MipLevels$LAYOUT, MipLevels$OFFSET, fieldValue);
    }

    private static final OfInt ArraySize$LAYOUT = (OfInt)$LAYOUT.select(groupElement("ArraySize"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * UINT ArraySize
     * }
     */
    public static final OfInt ArraySize$layout() {
        return ArraySize$LAYOUT;
    }

    private static final long ArraySize$OFFSET = 12;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * UINT ArraySize
     * }
     */
    public static final long ArraySize$offset() {
        return ArraySize$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * UINT ArraySize
     * }
     */
    public static int ArraySize(MemorySegment struct) {
        return struct.get(ArraySize$LAYOUT, ArraySize$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * UINT ArraySize
     * }
     */
    public static void ArraySize(MemorySegment struct, int fieldValue) {
        struct.set(ArraySize$LAYOUT, ArraySize$OFFSET, fieldValue);
    }

    private static final OfInt Format$LAYOUT = (OfInt)$LAYOUT.select(groupElement("Format"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * DXGI_FORMAT Format
     * }
     */
    public static final OfInt Format$layout() {
        return Format$LAYOUT;
    }

    private static final long Format$OFFSET = 16;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * DXGI_FORMAT Format
     * }
     */
    public static final long Format$offset() {
        return Format$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * DXGI_FORMAT Format
     * }
     */
    public static int Format(MemorySegment struct) {
        return struct.get(Format$LAYOUT, Format$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * DXGI_FORMAT Format
     * }
     */
    public static void Format(MemorySegment struct, int fieldValue) {
        struct.set(Format$LAYOUT, Format$OFFSET, fieldValue);
    }

    private static final GroupLayout SampleDesc$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("SampleDesc"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * DXGI_SAMPLE_DESC SampleDesc
     * }
     */
    public static final GroupLayout SampleDesc$layout() {
        return SampleDesc$LAYOUT;
    }

    private static final long SampleDesc$OFFSET = 20;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * DXGI_SAMPLE_DESC SampleDesc
     * }
     */
    public static final long SampleDesc$offset() {
        return SampleDesc$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * DXGI_SAMPLE_DESC SampleDesc
     * }
     */
    public static MemorySegment SampleDesc(MemorySegment struct) {
        return struct.asSlice(SampleDesc$OFFSET, SampleDesc$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * DXGI_SAMPLE_DESC SampleDesc
     * }
     */
    public static void SampleDesc(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, SampleDesc$OFFSET, SampleDesc$LAYOUT.byteSize());
    }

    private static final OfInt Usage$LAYOUT = (OfInt)$LAYOUT.select(groupElement("Usage"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * D3D11_USAGE Usage
     * }
     */
    public static final OfInt Usage$layout() {
        return Usage$LAYOUT;
    }

    private static final long Usage$OFFSET = 28;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * D3D11_USAGE Usage
     * }
     */
    public static final long Usage$offset() {
        return Usage$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * D3D11_USAGE Usage
     * }
     */
    public static int Usage(MemorySegment struct) {
        return struct.get(Usage$LAYOUT, Usage$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * D3D11_USAGE Usage
     * }
     */
    public static void Usage(MemorySegment struct, int fieldValue) {
        struct.set(Usage$LAYOUT, Usage$OFFSET, fieldValue);
    }

    private static final OfInt BindFlags$LAYOUT = (OfInt)$LAYOUT.select(groupElement("BindFlags"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * UINT BindFlags
     * }
     */
    public static final OfInt BindFlags$layout() {
        return BindFlags$LAYOUT;
    }

    private static final long BindFlags$OFFSET = 32;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * UINT BindFlags
     * }
     */
    public static final long BindFlags$offset() {
        return BindFlags$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * UINT BindFlags
     * }
     */
    public static int BindFlags(MemorySegment struct) {
        return struct.get(BindFlags$LAYOUT, BindFlags$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * UINT BindFlags
     * }
     */
    public static void BindFlags(MemorySegment struct, int fieldValue) {
        struct.set(BindFlags$LAYOUT, BindFlags$OFFSET, fieldValue);
    }

    private static final OfInt CPUAccessFlags$LAYOUT = (OfInt)$LAYOUT.select(groupElement("CPUAccessFlags"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * UINT CPUAccessFlags
     * }
     */
    public static final OfInt CPUAccessFlags$layout() {
        return CPUAccessFlags$LAYOUT;
    }

    private static final long CPUAccessFlags$OFFSET = 36;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * UINT CPUAccessFlags
     * }
     */
    public static final long CPUAccessFlags$offset() {
        return CPUAccessFlags$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * UINT CPUAccessFlags
     * }
     */
    public static int CPUAccessFlags(MemorySegment struct) {
        return struct.get(CPUAccessFlags$LAYOUT, CPUAccessFlags$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * UINT CPUAccessFlags
     * }
     */
    public static void CPUAccessFlags(MemorySegment struct, int fieldValue) {
        struct.set(CPUAccessFlags$LAYOUT, CPUAccessFlags$OFFSET, fieldValue);
    }

    private static final OfInt MiscFlags$LAYOUT = (OfInt)$LAYOUT.select(groupElement("MiscFlags"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * UINT MiscFlags
     * }
     */
    public static final OfInt MiscFlags$layout() {
        return MiscFlags$LAYOUT;
    }

    private static final long MiscFlags$OFFSET = 40;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * UINT MiscFlags
     * }
     */
    public static final long MiscFlags$offset() {
        return MiscFlags$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * UINT MiscFlags
     * }
     */
    public static int MiscFlags(MemorySegment struct) {
        return struct.get(MiscFlags$LAYOUT, MiscFlags$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * UINT MiscFlags
     * }
     */
    public static void MiscFlags(MemorySegment struct, int fieldValue) {
        struct.set(MiscFlags$LAYOUT, MiscFlags$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

