// Generated by jextract

package io.github.ghosthack.panama.media.d3d11video.jextract;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct D3D11_TEX2D_VDOV {
 *     UINT ArraySlice;
 * }
 * }
 */
public class D3D11_TEX2D_VDOV {

    D3D11_TEX2D_VDOV() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        d3d11video_h.C_INT.withName("ArraySlice")
    ).withName("D3D11_TEX2D_VDOV");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt ArraySlice$LAYOUT = (OfInt)$LAYOUT.select(groupElement("ArraySlice"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * UINT ArraySlice
     * }
     */
    public static final OfInt ArraySlice$layout() {
        return ArraySlice$LAYOUT;
    }

    private static final long ArraySlice$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * UINT ArraySlice
     * }
     */
    public static final long ArraySlice$offset() {
        return ArraySlice$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * UINT ArraySlice
     * }
     */
    public static int ArraySlice(MemorySegment struct) {
        return struct.get(ArraySlice$LAYOUT, ArraySlice$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * UINT ArraySlice
     * }
     */
    public static void ArraySlice(MemorySegment struct, int fieldValue) {
        struct.set(ArraySlice$LAYOUT, ArraySlice$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

