// Generated by jextract

package io.github.ghosthack.panama.media.d3d11video.jextract;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct D3D11_VIDEO_DECODER_OUTPUT_VIEW_DESC {
 *     GUID DecodeProfile;
 *     D3D11_VDOV_DIMENSION ViewDimension;
 *     union {
 *         D3D11_TEX2D_VDOV Texture2D;
 *     };
 * }
 * }
 */
public class D3D11_VIDEO_DECODER_OUTPUT_VIEW_DESC {

    D3D11_VIDEO_DECODER_OUTPUT_VIEW_DESC() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        _GUID.layout().withName("DecodeProfile"),
        d3d11video_h.C_INT.withName("ViewDimension"),
        MemoryLayout.unionLayout(
            D3D11_TEX2D_VDOV.layout().withName("Texture2D")
        ).withName("$anon$11682:5")
    ).withName("D3D11_VIDEO_DECODER_OUTPUT_VIEW_DESC");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final GroupLayout DecodeProfile$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("DecodeProfile"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * GUID DecodeProfile
     * }
     */
    public static final GroupLayout DecodeProfile$layout() {
        return DecodeProfile$LAYOUT;
    }

    private static final long DecodeProfile$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * GUID DecodeProfile
     * }
     */
    public static final long DecodeProfile$offset() {
        return DecodeProfile$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * GUID DecodeProfile
     * }
     */
    public static MemorySegment DecodeProfile(MemorySegment struct) {
        return struct.asSlice(DecodeProfile$OFFSET, DecodeProfile$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * GUID DecodeProfile
     * }
     */
    public static void DecodeProfile(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, DecodeProfile$OFFSET, DecodeProfile$LAYOUT.byteSize());
    }

    private static final OfInt ViewDimension$LAYOUT = (OfInt)$LAYOUT.select(groupElement("ViewDimension"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * D3D11_VDOV_DIMENSION ViewDimension
     * }
     */
    public static final OfInt ViewDimension$layout() {
        return ViewDimension$LAYOUT;
    }

    private static final long ViewDimension$OFFSET = 16;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * D3D11_VDOV_DIMENSION ViewDimension
     * }
     */
    public static final long ViewDimension$offset() {
        return ViewDimension$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * D3D11_VDOV_DIMENSION ViewDimension
     * }
     */
    public static int ViewDimension(MemorySegment struct) {
        return struct.get(ViewDimension$LAYOUT, ViewDimension$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * D3D11_VDOV_DIMENSION ViewDimension
     * }
     */
    public static void ViewDimension(MemorySegment struct, int fieldValue) {
        struct.set(ViewDimension$LAYOUT, ViewDimension$OFFSET, fieldValue);
    }

    private static final GroupLayout Texture2D$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("$anon$11682:5"), groupElement("Texture2D"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * D3D11_TEX2D_VDOV Texture2D
     * }
     */
    public static final GroupLayout Texture2D$layout() {
        return Texture2D$LAYOUT;
    }

    private static final long Texture2D$OFFSET = 20;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * D3D11_TEX2D_VDOV Texture2D
     * }
     */
    public static final long Texture2D$offset() {
        return Texture2D$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * D3D11_TEX2D_VDOV Texture2D
     * }
     */
    public static MemorySegment Texture2D(MemorySegment struct) {
        return struct.asSlice(Texture2D$OFFSET, Texture2D$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * D3D11_TEX2D_VDOV Texture2D
     * }
     */
    public static void Texture2D(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, Texture2D$OFFSET, Texture2D$LAYOUT.byteSize());
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

