// Generated by jextract

package io.github.ghosthack.panama.media.d3d11video.jextract;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct D3D11_VIDEO_DECODER_DESC {
 *     GUID Guid;
 *     UINT SampleWidth;
 *     UINT SampleHeight;
 *     DXGI_FORMAT OutputFormat;
 * }
 * }
 */
public class D3D11_VIDEO_DECODER_DESC {

    D3D11_VIDEO_DECODER_DESC() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        _GUID.layout().withName("Guid"),
        d3d11video_h.C_INT.withName("SampleWidth"),
        d3d11video_h.C_INT.withName("SampleHeight"),
        d3d11video_h.C_INT.withName("OutputFormat")
    ).withName("D3D11_VIDEO_DECODER_DESC");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final GroupLayout Guid$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("Guid"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * GUID Guid
     * }
     */
    public static final GroupLayout Guid$layout() {
        return Guid$LAYOUT;
    }

    private static final long Guid$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * GUID Guid
     * }
     */
    public static final long Guid$offset() {
        return Guid$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * GUID Guid
     * }
     */
    public static MemorySegment Guid(MemorySegment struct) {
        return struct.asSlice(Guid$OFFSET, Guid$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * GUID Guid
     * }
     */
    public static void Guid(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, Guid$OFFSET, Guid$LAYOUT.byteSize());
    }

    private static final OfInt SampleWidth$LAYOUT = (OfInt)$LAYOUT.select(groupElement("SampleWidth"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * UINT SampleWidth
     * }
     */
    public static final OfInt SampleWidth$layout() {
        return SampleWidth$LAYOUT;
    }

    private static final long SampleWidth$OFFSET = 16;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * UINT SampleWidth
     * }
     */
    public static final long SampleWidth$offset() {
        return SampleWidth$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * UINT SampleWidth
     * }
     */
    public static int SampleWidth(MemorySegment struct) {
        return struct.get(SampleWidth$LAYOUT, SampleWidth$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * UINT SampleWidth
     * }
     */
    public static void SampleWidth(MemorySegment struct, int fieldValue) {
        struct.set(SampleWidth$LAYOUT, SampleWidth$OFFSET, fieldValue);
    }

    private static final OfInt SampleHeight$LAYOUT = (OfInt)$LAYOUT.select(groupElement("SampleHeight"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * UINT SampleHeight
     * }
     */
    public static final OfInt SampleHeight$layout() {
        return SampleHeight$LAYOUT;
    }

    private static final long SampleHeight$OFFSET = 20;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * UINT SampleHeight
     * }
     */
    public static final long SampleHeight$offset() {
        return SampleHeight$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * UINT SampleHeight
     * }
     */
    public static int SampleHeight(MemorySegment struct) {
        return struct.get(SampleHeight$LAYOUT, SampleHeight$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * UINT SampleHeight
     * }
     */
    public static void SampleHeight(MemorySegment struct, int fieldValue) {
        struct.set(SampleHeight$LAYOUT, SampleHeight$OFFSET, fieldValue);
    }

    private static final OfInt OutputFormat$LAYOUT = (OfInt)$LAYOUT.select(groupElement("OutputFormat"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * DXGI_FORMAT OutputFormat
     * }
     */
    public static final OfInt OutputFormat$layout() {
        return OutputFormat$LAYOUT;
    }

    private static final long OutputFormat$OFFSET = 24;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * DXGI_FORMAT OutputFormat
     * }
     */
    public static final long OutputFormat$offset() {
        return OutputFormat$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * DXGI_FORMAT OutputFormat
     * }
     */
    public static int OutputFormat(MemorySegment struct) {
        return struct.get(OutputFormat$LAYOUT, OutputFormat$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * DXGI_FORMAT OutputFormat
     * }
     */
    public static void OutputFormat(MemorySegment struct, int fieldValue) {
        struct.set(OutputFormat$LAYOUT, OutputFormat$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

