// Generated by jextract

package io.github.ghosthack.panama.media.d3d11video.jextract;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct _DXVA_Qmatrix_H264 {
 *     UCHAR bScalingLists4x4[6][16];
 *     UCHAR bScalingLists8x8[2][64];
 * } DXVA_Qmatrix_H264
 * }
 */
public class DXVA_Qmatrix_H264 extends _DXVA_Qmatrix_H264 {

    DXVA_Qmatrix_H264() {
        // Should not be called directly
    }
}

