// Generated by jextract

package io.github.ghosthack.panama.media.d3d11video.jextract;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct _DXVA_Slice_H264_Short {
 *     UINT BSNALunitDataLocation;
 *     UINT SliceBytesInBuffer;
 *     USHORT wBadSliceChopping;
 * } DXVA_Slice_H264_Short
 * }
 */
public class DXVA_Slice_H264_Short extends _DXVA_Slice_H264_Short {

    DXVA_Slice_H264_Short() {
        // Should not be called directly
    }
}

